#!/usr/bin/perl
# safe 070205
use strict;
use CGI ":standard";
use Fcntl qw(:flock O_RDWR O_CREAT O_RDONLY);
use Digest::MD5 "md5_hex";

BEGIN {chdir "/home/aw/inc";}
use awstandard;
use awinput;
awstandard_init();

print AWheader("admin");

my %options;
my %db;
for my $p (qw'pw user awname') {
   $options{$p}=lc(param($p));
   $options{$p}=~s/[<>]//g; # min sanitize user input
}
if($options{user} && md5_hex('sAlty'.$options{pw}) eq '3b8614d7b6019df32e86f35b1ed300dd') {
   awinput::opendb(O_RDWR|O_CREAT, "/home/aw/db2/rsamap.dbm", \%db);
   if($options{awname}) {
#      my $x=awstandard::urldecode($options{user});
      $db{$options{user}}=$options{awname};
      print "added $options{user}=$options{awname}";
   } else {
      delete $db{$options{user}};
      print "deleted $options{user}";
   } 
   untie(%db);
} 

# form
print start_form(-method=>'get', -name=>"form"), 
      textfield(-name=>'user', -class=>'text'), " RSA user name", br.AWfocus("form.user"),
      textfield(-name=>'awname', -class=>'text'), " AW user name",br,
      password_field(-name=>'pw', -class=>'text'), " pw",br,
      submit(-class=>'smbutton'),
      end_form;

print AWtail();
