#!/usr/bin/perl
# safe 070205
use strict;
use CGI ":standard";
use Fcntl qw(:flock O_RDWR O_CREAT O_RDONLY);
use Digest::MD5 "md5_hex";


use DBAccess2;
use awstandard;
use awinput;
use awsql;
awstandard_init();

print AWheader("admin");

my %options;
my %db;
for my $p (qw'pw user alli') {
   $options{$p}=lc(param($p));
   $options{$p}=~s/[<>]//g; # min sanitize user input
}
my $pid=playername2idm($options{user});
if($options{user} && $pid && md5_hex('sAltx'.$options{pw}) eq 'd954c6b3f0a24db8fbfd435f3daac7e9') {
   awinput::opendb(O_RDWR|O_CREAT, "$awstandard::dbmdir/useralli.dbm", \%db);
   set_useralli($pid,$options{alli});
   if($options{alli}) {
#      my $x=awstandard::urldecode($options{user});
      $db{$options{user}}=$options{alli};
      print "added $options{user}=$options{alli}";
   } else {
      print "$options{user} = $db{$options{user}} ... ";
      delete $db{$options{user}};
      print "deleted $options{user}";
   } 
   untie(%db);
} 

# form
print start_form(-method=>'get', -name=>"form"), 
      textfield(-name=>'user', -class=>'text'), " user name", br.AWfocus("form.user"),
      textfield(-name=>'alli', -class=>'text'), " alli",br,
      password_field(-name=>'pw', -class=>'text'), " pw",br,
      submit(-class=>'smbutton'),
      end_form;

print AWtail();

