#!/usr/bin/perl -w
use strict;
use CGI ":standard";

use awstandard;
use awinput;

our %options;
print AWheader("AW alli account creation tool");
my $pid=getauthpid();
if(!is_founder($pid) && !is_admin()) {
	print "sorry, this tool is only for players with founder permissions\n";
	exit 0;
}

awinput_init();
my $tag=playerid2tagm($pid);
if($ENV{REQUEST_METHOD} eq "POST" && param()) {
	foreach my $p (qw(p)) {
		$options{$p}=param($p);
#      if(defined($options{$p})){$options{$p}=~s/[^0-9]//g;} # sanitize user input;
	}
   #if($options{p}){$options{p}=~s/[^0-9]//g;} # sanitize user input;
#	my $aid=playerid2alliance($pid);
#print " tag=$tag\n",br;
	if($options{p} ne "yes") {
		print "you must say 'yes'",br;
	} elsif($tag && $tag=~m/^[a-zA-Z]{1,4}$/) {
		my $ltag=lc($tag);
		settoolsaccess($ltag,$ltag,255,255,2);
		mkdir("html/alli/$ltag");
		print "added extended tools access for tag=$tag";
	} else {
		print "something failed. can not add tag=$tag";
	}
} else {
	print start_form(-name=>"form"),textfield(-name=>'p', -class=>'text')," type 'yes' here, if you want an extended AWTools account for '$tag' and agree to <a href=\"http://$bmwserver/manual/manual.html#policy\">the AWTools NAP rules</a>",br,br,
	"Note: if you do not want an AWTools NAP, you can click the pay-button there",br,
		submit(-name=>"create account", -class=>'smbutton'),end_form.AWfocus("form.p");
}
print AWtail();

