#!/usr/bin/perl
use strict;
use CGI qw":standard *table";
chdir "/home/bernhard/code/cvs/perl/awcalc";
require "input.pm";
require "cgicommon.pm";

my %options;
my $align="left";
print AWheader("alliance info", 
      "<style> th, td { font-family: monospace; 
      border-left: 1px solid gray;  
      border-bottom: 1px solid gray; } </style>
");
#print header, start_html($title), h1($title);
for my $p (qw'alliance') {
	$options{$p}=param($p);
}

if($options{alliance}) {
	my $n=0;
	my $alli="\U$options{alliance}\E";
	my $aid=alliancetag2id($alli);
	my $own=("\L$alli" eq $ENV{REMOTE_USER});
	if(!$aid) {
		print "unknown alliance";
		exit(0);
	}
   my %pointsdb;
   tie(%pointsdb, "DB_File", "/home/bernhard/db/points.dbm");
   my @alliancepoints;

   my $forumlink=$::alliances{$aid}{url}||"";
   my $allitag=$::alliances{$aid}{tag}||"";
   my $alliname=$::alliances{$aid}{name}||"";
   if($forumlink) {$forumlink=" URL:".a({-href=>$forumlink}, $forumlink)}
	my $rellink=qq! <a href="relations?name=$alli"><img src="/images/aw/relations-colored.gif" title="alliance info" alt="alliance info" /></a> !;
	print a({-href=>"http://$::server/rankings/alliances/$allitag.php"},"$alliname (AW)").$rellink." ".a({-href=>"http://azgharde.celeonet.fr/tools/alliances.php?tag=$alli"},"azgharde").$forumlink.br."\n";
   my @members=allianceid2members($aid);
	print "$alli members (".scalar @members.")",br,start_table();
	print "<tr align=\"$align\">".th("links").th("name").th("home").th("pl").th("sl").th("cl").th("pts(rank)").th("log").th("from").th("joined").th("intel")."</tr>\n";
	my @totalprod=(0,0,0);
	my @totalres=(0,0);
   my $totalcul=0;
   my $totalpl=0;
	for my $pid (@members) {
		my $p=$::player{$pid};
		next if ! defined($p);
		next if $$p{alliance} ne $aid;
		print "<tr align=\"$align\">";
		my $name=playerid2name($pid);
      if($pointsdb{$name}) {
         push(@alliancepoints, $pointsdb{$name});
      }
		my $alink="";
		my $planets=playerid2planets($pid);
		my $joined=gmtime($$p{joined});#." ".$$p{joined};
		my ($x,$y)=systemid2coord($$p{home_id});
		my $home="$$p{home_id}($x,$y)";
		my @rel=getrelation($name);
      my @race=relation2race($rel[2]);
      my @science=relation2science($rel[2]);
		my @prod=relation2production($rel[2]);
      my $bonus=pop(@prod);
		{ my $n=0;
                        foreach(@prod[0..2]) { $_*=$$bonus[$n]; $totalprod[$n]+=$_; $n++}
                        for(0..1) { $totalres[$_]+=$prod[$_+5];}
                }
		if($own) { $alink=alliancedetailslink($n) }
      my $intel="-";
      my $bio25=0;
      if(defined($science[0]) && $science[0]>100) {
         $intel=int((time()-$science[0])/3600/24)."d";
         if($science[1]>=25) {$bio25=1}
         if($science[8]) {
            my $diff=$science[8]-time();
            my $etc=sprintf(" %.1fh",(int($science[8])-time())/3600);
            if($diff<24*3600 && ($diff<-60*3600 || $diff>-20*3600)) { $intel.=span({-style=>"color:red"},$etc)}
            else {$intel.=$etc;}
            
         }
      }
      if(defined($race[0])) {$race[7]=".+".-$race[7];$intel=join("",@race)." ".$intel;}
      if($bio25) {$intel=div({-style=>"color:green"},$intel)}
      my $cplanets="$planets/$$p{culture}";
      $totalcul+=$$p{culture};
      $totalpl+=$$p{level};
      my $planetscolor="";
      if($$p{culture}-$planets>1) {$planetscolor=' style="color:red"'}
      if($$p{culture}-$planets==1) {$planetscolor=' style="color:brown"'}
		print "<td>",profilelink($pid), $alink, "</td><td>", qq!<a href="relations?name=$name">$name ($pid)</a></td>
		<td><a href="system-info?id=$$p{home_id}">$home</a></td><td>$$p{level}</td><td>$$p{science}</td><td$planetscolor>$cplanets</td><td>$$p{points}(#$$p{rank})</td><td>$$p{logins}</td><td>!.playerid2country($pid).qq!</td><td>$joined</td><td>$intel</td>!;
		$n++;
		print "</tr>\n";
	}
	print end_table();
   if(scalar @alliancepoints == scalar @members) {
      my $counted=@members;
      if($counted>=10) {$counted-=int(($counted-5)/5)}
      @alliancepoints = reverse sort @alliancepoints;
#print "$counted: @alliancepoints\n".br;
      my $sum=0;
      foreach(@alliancepoints[0..$counted-1]) { $sum+=$_ }
      printf "current alliance score: %.2f".br,($sum/$counted);
      
   }
   printf "average culture: %.2f".br,($totalcul/@members);
   printf "average PL: %.2f".br,($totalpl/@members);
	if($totalprod[0]) {
      print "total hourly production/science/culture: ".join(" / ", @totalprod).br;
      print "total saved A\$ / PP: ".join(" / ", @totalres).br;
   }
} else {
	print start_form(-method=>'get', -name=>"form"), textfield(-name=>'alliance', -class=>'text'), " alliance tag", br,
	 submit(-name=>"query", -class=>'smbutton'),end_form.AWfocus("form.alliance");
}
print end_html;
