#!/usr/bin/perl
use strict;
use CGI qw":standard *table";
chdir "/home/bernhard/code/cvs/perl/awcalc";
require "input.pm";
require "cgicommon.pm";

my %options;
print AWheader("alliance info");
#print header, start_html($title), h1($title);
for my $p (qw'alliance') {
	$options{$p}=param($p);
}

if($options{alliance}) {
	my $n=0;
	my $alli="\U$options{alliance}\E";
	my $aid=alliancetag2id($alli);
	my $own=("\L$alli" eq $ENV{REMOTE_USER});
	if(!$aid) {
		print "unknown alliance";
		exit(0);
	}
	my $rellink=qq! <a href="relations?name=$alli"><img src="/images/aw/relations-colored.gif" title="alliance info" alt="alliance info" /></a> !;
	print a({-href=>"http://$::server/rankings/alliances/$alli.php"},"$alli (AW)").$rellink." ".a({-href=>"http://azgharde.celeonet.fr/tools/alliances.php?tag=$alli"},"azgharde").br;
	print "$alli members",br,start_table();
	print "<tr align=\"center\"><td>links</td><td>name</td><td>home</td><td>pl</td><td>sl</td><td>cl</td><td>points(rank)</td><td>log</td><td>from</td><td>joined</td></tr>\n";
	my @totalprod=(0,0,0);
	for my $pid (allianceid2members($aid)) {
		my $p=$::player{$pid};
		next if ! defined($p);
		next if $$p{alliance} ne $aid;
		print "<tr align=\"center\">";
		my $name=playerid2name($pid);
		my $alink="";
		my $planets=playerid2planets($pid);
		my $joined=gmtime($$p{joined});#." ".$$p{joined};
		my ($x,$y)=systemid2coord($$p{home_id});
		my $home="$$p{home_id}($x,$y)";
		my @rel=getrelation($name);
		my @prod=relation2production($rel[2]);
		{ my $n=0;
                        foreach(@prod[0..2]) { $_*=$prod[$n+5]; $totalprod[$n]+=$_; $n++}
                }
		if($own) { $alink=alliancedetailslink($n) }
		print "<td>",profilelink($pid), $alink, "</td><td>", qq!<a href="relations?name=$name">$name ($pid)</a></td>
		<td><a href="system-info?id=$$p{home_id}">$home</a></td><td>$$p{level}</td><td>$$p{science}</td><td>$planets/$$p{culture}</td><td>$$p{points}(#$$p{rank})</td><td>$$p{logins}</td><td>!.playerid2country($pid).qq!</td><td>$joined</td>!;
		$n++;
		print "</tr>\n";
	}
	print end_table();
	if($totalprod[0]) { print "total hourly production/science/culture: ".join(", ", @totalprod);}
} else {
	print start_form('get'), textfield(-name=>'alliance', -class=>'text'), " alliance tag", br,
	 submit(-name=>"query", -class=>'smbutton'),end_form
}
print end_html;
