#!/usr/bin/perl
use strict;
use CGI qw":standard *table";

use awstandard;
use awinput;
awinput_init();

my %options;
my $align="left";
print AWheader("alliance info");
#print header, start_html($title), h1($title);
for my $p (qw'alliance') {
	$options{$p}=param($p);
   $options{$p}=~s/[^-+a-zA-Z0-9.]//g; # sanitize user input
}
$options{alliance}||=$ENV{REMOTE_USER};
if($options{alliance} eq "guest") {$options{alliance}=""}

if($options{alliance}) {
	my $alli="\U$options{alliance}\E";
	my $aid=alliancetag2id($alli);
	my $own=("\L$alli" eq $ENV{REMOTE_USER});
   my @members=allianceid2members($aid);
   print "showing all \U$ENV{REMOTE_USER}\E alliance pages on one page (does not work with some browser versions)".br;
   for my $n (0..(scalar @members -1)) {
   	print qq'<iframe width="95%" height="700" src="http://$awserver/0/Alliance/Detail.php/?id=$n"></iframe><br />';
   }
} else {
	print start_form(-method=>'get', -name=>"form"), textfield(-name=>'alliance', -class=>'text'), " alliance tag", AWfocus("form.alliance"), br,
	 submit(-name=>"query", -class=>'smbutton'),end_form
}
print AWtail();
