#!/usr/bin/perl

use strict;
use CGI ":standard";
BEGIN {chdir "/home/bernhard/code/cvs/perl/awcalc";}
use awstandard;
use arrival;
awstandard_init();

my %options=qw;
racespeed 0
energy 0
distance 0
planet 0
own 0
;;

print AWheader('Arrival time calculator');
printform();
if(param()) {
#require "arrival.pm";
	for my $p (qw'planet distance own energy racespeed') {
	  $options{$p}=param($p);
	  if(!$options{$p}) {$options{$p}=0}
	}
   my $eenergy=sprintf("%.2f", arrival::effectiveenergy($options{racespeed},$options{energy}));
	my $time=arrival::traveltime(\%options);
	my $h=int($time);
	my $m=int(($time-$h)*60);
	print h2("results")."distance/planets: ".sprintf("%.2f",sqrt($options{distance}))."=&radic;".span({-style=>"text-decoration:overline;"},$options{distance})." / $options{planet}".br."energy/speed/xEnergy: $options{energy} / $options{racespeed} / $eenergy".br."allied destination: ".($options{own}?"yes":"no").br.br;
	printf "time %.3fh = %2i:%.2i".br, $time, $h, $m;
#	my ($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = 
   print "ETA ".AWtime(time()+$time*3600);
#	$year+=1900;$mon++;
#	printf "ETA %.2i.%.2i.%i %2i:%.2i:%.2i GMT".br, $mday,$mon,$year, $hour,$min,$sec;
} 

sub printform { 
	my $s=5;
	print start_form(-method=>'get', -name=>"form"),
	textfield(-name=>'planet', -size=>$s, -class=>'text'), " Planet difference", br.AWfocus("form.planet"),
	textfield(-name=>'distance', -size=>$s, -class=>'text'), " ",a({-href=>"distsqr"},"Distance squared"), br,
	textfield(-name=>'energy', -size=>$s, -class=>'text'), " Energy level", br,
	popup_menu(-name=>'racespeed', -values=>[-4..4], -default=>0), " Race speed modifier", br,
	checkbox(-name=>'own', -label=>''), " Own or allied destination", br,
	  submit(-class=>'smbutton'), end_form, p.
'When going from Planet a in System A(x/y) to Planet b in System B(X/Y) then '.br.'Planet diff is the absolute of a-b  and  Dist sqr is (x-X)<sup>2</sup>+(y-Y)<sup>2</sup>'.
#br.'Energy level accepts fractions like 10.5'.
br.'leaving fields blank counts as zero'.br;
}
print end_html;

