#!/usr/bin/perl -w
# probably safe 070204
use strict;
use CGI ":standard";

use awstandard;
awstandard_init();

our %options;
if(param("session")) {
	foreach my $p (qw(session uri)) {
		$options{$p}=param($p);
	}
   if($options{session}) {
		my $uri2=$ENV{QUERY_STRING};
		if($uri2=~m/uri=(.*)/) {$options{uri}=$1} # allow for normal & chars
      $options{uri}||="/cgi-bin/index.html";
      $options{uri}=~s/%(\D)/&$1/g;
      print redirect(-connection=>"Keep-Alive", -uri=>$options{uri}, -cookie=>[#cookie(-name=>'sessionid', -value=>$options{session}, -expires=>'+2d'), 
            cookie(-name=>'PHPSESSID', -value=>$options{session}, -expires=>'+2d')]);
#      print header(-cookie=>[cookie(-name=>'sessionid', -value=>$options{session}, -expires=>'+7d')])
   }
} else {
   print AWheader("AW authentication");
	print start_form(),textfield(-name=>'session', -class=>'text'), "AW's PHPSESSID cookie", br,
		submit(-name=>"query", -class=>'smbutton'),end_form.AWfocus("form.session");
print AWtail();
}

