#!/usr/bin/perl -w
use strict;
use CGI ":standard";

use awstandard;
use awinput;
use DBAccess2;
awstandard_init();
#awinput_init();

our %options;
print AWheader("AW battles");
if(param()) {
	foreach my $p (qw(p sid atag1 atag2 atime btime)) {
		$options{$p}=param($p);
#      if(defined($options{$p})){$options{$p}=~s/[^0-9]//g;} # sanitize user input;
	}
   if((my $pn=param('pn'))) {$options{p}=playername2idm($pn)}
   if($options{p}){$options{p}=~s/[^0-9]//g;} # sanitize user input;
   if($options{sid}){$options{sid}=~s/[^0-9]//g;} # sanitize user input;

   my @filters;
   if($options{p}) { push(@filters, "pid = $options{p}") }
   if($options{sid}) { push(@filters, "system_id = $options{sid}") }
   my $allitab="";
   foreach my $a (qw(atag1 atag2)) {
      if($options{$a}) {
#         $allitab=",alliances";
         my $aid=alliancetag2id($options{$a});
         push(@filters, "alliance = $aid");
      }
   }
#   SELECT * FROM battles LEFT JOIN player AS p1 ON def_id=p1.pid LEFT JOIN player AS p2 ON att_id=p2.pid WHERE
   my $sql="SELECT * FROM battles,player$allitab WHERE (def_id=pid OR att_id=pid) AND ".join(" AND ",@filters);
   print $sql.br;
   my $dbh=get_dbh();
   my $res=$dbh->selectall_arrayref($sql);
   my @data;
   foreach my $row(@$res) {
      push(@data,[@$row]);
   }
   foreach(@data) {
      print join(" ",@$_),br,"\n";
   }
   
} else {
   if(!param('atime')) { param('atime',AWisodate(time-3600*24*3)); }
	print start_form(-name=>"form",-method=>'get'),textfield(-name=>'pn', -class=>'text'),' player',br,
         textfield(-name=>'sid', -class=>'text'),' system ID',br,
         textfield(-name=>'atag1', -class=>'text'),' alliance',br,
         textfield(-name=>'atag2', -class=>'text'),i(' AND fighting alliance'),br,
         textfield(-name=>'btime', -class=>'text'), " ",checkbox(-name=>'btimeon',-label=>"before"),br,
         textfield(-name=>'atime', -class=>'text'), " ",checkbox(-name=>'atimeon',-label=>"after"),br,
		submit(-name=>"query", -class=>'smbutton'),end_form.AWfocus("form.pn");
}
print AWtail();

