#!/usr/bin/perl -w
use strict;
use CGI ":standard";

use DBAccess2;
use awstandard;
use awinput;
use awsql;
awstandard_init(); # for tool theming
#awinput_init();

our %options;
if(param()) {
	foreach my $p (qw(p)) {
		$options{$p}=param($p);
	}
   if($options{p}){$options{p}=~s/[^0-9]//g;} # sanitize user input;
   my $p=$options{p};
   print header("text/plain");
   if($p==1) {
   } elsif($p==2) {
      my $dbh=get_dbh;
      my $res=$dbh->selectall_arrayref("
            SELECT *
            FROM `cdcv` 
         ");
      foreach(@$res) {
         print join("\t", @$_),"\n";
      }
   } elsif($p==3) {
      my $dbh=get_dbh;
      my $res=$dbh->selectall_arrayref("
            SELECT *
            FROM `cdlive` 
         ");
      foreach(@$res) {
         print join("\t", @$_),"\n";
      }
   } elsif($p==29) {
      my $dbh=get_dbh;
      my ($allimatch,$amvars)=get_alli_match2($ENV{REMOTE_USER}, 1);
      my $sth=$dbh->prepare("
            SELECT `fleets`.*
            FROM `fleets`, `toolsaccess`
            WHERE $allimatch
         ");
      my $res=$dbh->selectall_arrayref($sth,{},@$amvars);
      foreach(@$res) {
         print join("\t", @$_),"\n";
      }

   } elsif($p==30) {
      my $dbh=get_dbh;
      my $tab="battlecalc";
      my $fields=get_table_fields($tab);
      print (join("\t",@$fields),"\n");
      my $res=$dbh->selectall_arrayref("
            SELECT * FROM `$tab`
         ");
      foreach(@$res) {
         print join("\t", @$_),"\n";
      }
   }
} else {
   print AWheader("AW CD data tool");
	print start_form(-name=>"form", -method=>"get"),
#      textfield(-name=>'p', -class=>'text'),br,
      popup_menu(-name=>'p',-values=>[2..3], -labels=>{1=>"score",2=>"CV",3=>"points+PL"})," type of dump",br,
		submit(-name=>"query", -class=>'smbutton'),end_form,
      br,"During countdown, this tool will export live data for use in other tools. When your tool gets many hits, it would be nice if you rate-limit requests to one per minute and cache the result in between."
      ;
#.AWfocus("form.p");
   print AWtail();
}

