#!/usr/bin/perl -w
use strict;
use CGI ":standard";

use DBAccess2;
use awstandard;
use awinput;
use awsql;
use DBDump;
awstandard_init(); # for tool theming
#awinput_init();

our %options;
if(param()) {
	foreach my $p (qw(p)) {
		$options{$p}=param($p);
	}
   if($options{p}){$options{p}=~s/[^0-9]//g;} # sanitize user input;
   my $p=$options{p};
   my $alli=$ENV{REMOTE_USER};
   print header("text/plain");
   if($p==1) {
   } elsif($p==2) {
      dumpwholetable("cdcv");
   } elsif($p==3) {
      dumpwholetable("cdlive");
   } elsif($p==15) {
      dumpwholetable("playerextra");
   } elsif($p==20) {
		dumptable("intelreport", $alli, 4);
   } elsif($p==21) {
		dumptable("internalintel", $alli, 32);
   } elsif($p==24) {
      dumptable("planetinfos", $alli, 2);
   } elsif($p==26) {
      dumptable("relations", $alli, 8);
   } elsif($p==27) {
      dumptable("allirelations", $alli, 8);
   } elsif($p==29) {
      dumptable("fleets", $alli, 1);
   } elsif($p==30) {
      dumpwholetable("battlecalc");
   } elsif($p==200) {
      my $sidpid=sidpid22sidpid3m(param("sid"),0);
      if($sidpid>12) {
	      dumptable2("planets", "SELECT * FROM `planets` WHERE sidpid>=? AND sidpid<=?", [$sidpid, $sidpid+12]);
      }
   }
} else {
   print AWheader("AW CD data tool");
	print start_form(-name=>"form", -method=>"get"),
#      textfield(-name=>'p', -class=>'text'),br,
      popup_menu(-name=>'p',-values=>[2..3], -labels=>{1=>"score",2=>"CV",3=>"points+PL"})," type of dump",br,
		submit(-name=>"query", -class=>'smbutton'),end_form,
      br,"During countdown, this tool will export live data for use in other tools. When your tool gets many hits, it would be nice if you rate-limit requests to one per minute and cache the result in between."
      ;
#.AWfocus("form.p");
   print AWtail();
}

