#!/usr/bin/perl
# safe 070204
use strict;
use CGI ":standard";

use awmap;

my %options;
for my $p (qw'x y xs ys scale') {
  $options{$p}=param($p);
  $options{$p}=~s/[^-+0-9.]//g; # sanitize user input (just to be sure)
}
if(defined($options{x}) && defined($options{y})) {
	if(defined($options{xs})) {
		$mapxoff=$options{xs};
		$mapyoff=$options{ys};
	}
	if(!$options{scale}) {$options{scale}=1}
	my($x,$y)=awmap::imgtomap($options{x}/$options{scale}, $options{y}/$options{scale}, $mapxoff, $mapyoff);
	my $target=$ENV{SCRIPT_NAME};
	$target=~s/coord/system-info/;
	print redirect("http://$ENV{HTTP_HOST}$target?mapx=$x&mapy=$y");
} else {
   print header(),"need coords from ".a({-href=>"tactical"},"tactical");
}

