#!/usr/bin/perl -w

use strict;
use CGI ":standard";
BEGIN {chdir "/home/aw/inc";}
use awstandard;
use awinput;
awinput_init();

my %options=qw;
;;

print AWheader('Distance calculator');
print "calculation of euclidian distance square value for ".a({-href=>"arrival"},"arrival time calculation").p;
if(param()) {
 for my $p (qw'dx dy sx sy sid did') {
  $options{$p}=param($p);
 }
 if($options{sid}) { ($options{sx},$options{sy})=systemid2coord($options{sid}); }
 if($options{did}) { ($options{dx},$options{dy})=systemid2coord($options{did}); }
 my $dx=$options{sx}-$options{dx};
 my $dy=$options{sy}-$options{dy};
 print "from ($options{sx},$options{sy}) to ($options{dx},$options{dy}) is distance ($dx,$dy) so \n".br;
 my $d=$dx**2+$dy**2;
 print a({href=>"arrival?distance=$d"},"distsqr=$d");
} else { 
  my $s=4;
  print start_form(-method=>'get', -name=>"form"),
   textfield(-name=>'sx', -size=>$s, -class=>'text'), " x ", textfield(-name=>'sy', -size=>$s, -class=>'text'), " y - or id: ", textfield(-name=>'sid', -size=>$s+1, -class=>'text'), " starting location", br,
   textfield(-name=>'dx', -size=>$s, -class=>'text'), " x ", textfield(-name=>'dy', -size=>$s, -class=>'text'), " y - or id: ", textfield(-name=>'did', -size=>$s+1, -class=>'text'), " destination location", br,
   submit(-class=>'smbutton'), end_form;
}
print AWtail();

#awinput::awinput_finish();
