#!/usr/bin/perl -w
# safe 070204
use strict;
use CGI ":standard";

BEGIN {chdir "/home/aw/inc";}
use awstandard;
use awinput;
use DBAccess;
#awstandard_init();
awinput_init();

our %options;
print AWheader("AW edit fleet-info");
if(param()) {
	foreach my $p (qw(fid info)) {
		$options{$p}=param($p);
	}
   if(defined($options{info}) && $options{fid}) { # set entry
      $options{info}=~s/[<>]//g; # minimal sanitation # TODO
      $options{fid}=~s/[^0-9]//g;
      my $sth=$dbh->prepare("UPDATE `fleets` SET `info` = ? WHERE `fid` = ? AND `alli` = ?");
      my $res=$sth->execute($options{info}, $options{fid}, $ENV{REMOTE_USER});
      if($res && $res>0) {
         print "entry $options{fid} updated".br.br;
      }
   }
   my $res=awinput::get_fleet($options{fid});
   foreach my $row (@$res) {
#         foreach my $c (
      print awinput::show_fleet($row).br;
      print "raw data: @$row".br;
      my ($sidpid,$info)=@$row[3,$#$row];
      my $sid=awinput::sidpid2sidm($sidpid);
      my $pid=awinput::sidpid2pidm($sidpid);
      print "planet: ".a({-href=>"planet-info?id=$sid%23$pid"}, "$sid#$pid")." system: ".a({-href=>"system-info?id=$sid"}, $sid).br;
      print start_form(-name=>"form").hidden('fid').textfield(-name=>'info', -class=>'text', -value=>$info)." fleet info".br.submit(-name=>"set", -class=>'smbutton').end_form.AWfocus("form.info");
   }
} else {
	print start_form(-method=>'get', -name=>"form"),textfield(-name=>'fid', -class=>'text')," fleet id",br,
		submit(-name=>"query", -class=>'smbutton'),end_form.AWfocus("form.fid");
}
print AWtail();

