#!/usr/bin/perl -w
use strict;
use CGI ":standard";

BEGIN {chdir "/home/aw/inc";}
use awstandard;
use awinput;
#awstandard_init();
awinput_init();

my $awuser=cookie('user');
my $refsys=cookie('refsys');

our %options;
if($refsys && param()) {
	foreach my $p (qw(sid pid)) {
		$options{$p}=param($p);
	}
   my($refe,$refs)=(0,0);
   my($refsid,$refpid)=split(/[^0-9]/,$refsys);
   $refpid||=0;
   my($refx,$refy)=systemid2coord($refsid);
   my($x,$y)=systemid2coord($options{sid});
   $refx||=0;
   $refy||=0;
   $x||=0;
   $y||=0;
   my $refdist=($refx-$x)**2+($refy-$y)**2;
   if(defined($awuser)) {
      my($race,$sci)=awinput::playername2ir($awuser);
      if($race) {$refs=$$race[4];$refs=~s/\+//;}
      if($sci) {if($$sci[0]>99){shift(@$sci)};$refe=$$sci[2]}
   }
   my $pdiff=abs($refpid-$options{pid});
   #print header(), "eta for: $refsid#$refpid -> $options{sid}#$options{pid}";
   print redirect("/cgi-bin/arrival?distance=$refdist&amp;planet=$pdiff&amp;energy=$refe&amp;racespeed=$refs");

} else {
   print AWheader("AW ETA tool"). "This tool uses the value from refsys cookie as second coord which can be ".a({-href=>"preferences"},"set in preferences")." or system-info tools".br;
	print start_form(-name=>"form", -method=>"get"),
      textfield(-name=>'sid', -class=>'text')," sid",br,
      textfield(-name=>'pid', -class=>'text')," pid",br,
		submit(-name=>"query", -class=>'smbutton'),end_form.AWfocus("form.sid");
   print AWtail();
}

