#!/usr/bin/perl -w
use strict;
use CGI ":standard";

#print "Content-Type: text/html\n\n";

BEGIN {chdir "/home/bernhard/code/cvs/perl/awcalc";}
use awstandard;
use awinput;
use mangle::dispatch;
use feed::dispatch;
awinput_init();

my %options;
my $title="mangling AW feed update";
my $debug=0;
foreach my $p (qw(tz html file debug name url)) {
	$options{$p}=param($p);
}
if(param()) {
	my $html=$options{html};
	if(upload('file')) {
#print "uploaded file $options{file}\n".br;
		my $bytes_read=read(upload('file'), $html, 40000);
		#print $bytes_read;
	}
#	print "input ",length($html)," bytes".br;
	if($debug) {
		open(DEBUG, ">> /tmp/debug");
		print DEBUG time(),"\n";
		foreach(keys(%options)) {
			my $entry=$_."=";
			if($options{$_}){$entry.=$options{$_}}
			print DEBUG $entry,"\n";
		}
	}
   $_=$html;
#   require "./mangle/dispatch.pm";
   mangle::dispatch::mangle_dispatch(\%options);
  
   print header(), $_;
   open(STDOUT, ">", "/dev/null");
#	require './feed/dispatch.pm';
   feed::dispatch::feed_dispatch($html, \%options);
} else {
print AWheader($title);
	my $uc=cookie('user');
	if(!$options{name}) {param("name",$uc)}
   if($::timezone){}#dummy
	print start_form(-method=>'post',-enctype=>"multipart/form-data", -name=>"form"),
	textfield(-name=>'tz', -value=>$::timezone, -class=>'text'), " timezone of subject: GMT+n", br,
	textfield(-name=>'name',-value=>'', -class=>'text'), " who reports (e.g. for own fleet movements)", br,
	textarea(-name=>'html',-value=>"", -cols=>40, -rows=>9, -class=>'text'), " copy+paste HTML source here", br,
	filefield(-name=>'file', -class=>'file'), " or upload a downloaded HTML file", br.AWfocus("form.html"),
#	checkbox('debug'), br,
	submit(-name=>'add data', -class=>'smbutton'), reset(-class=>'smbutton'), end_form, 
   end_html;
}
awinput::awinput_finish();
