#!/usr/bin/perl -w

use strict;
use CGI ":standard";

use awstandard;
use awinput;
use DBAccess;
awinput_init(1);
my $alli=$ENV{REMOTE_USER};
my $title="fleets [\U$alli\E]";
my $wantcurrent=" AND `iscurrent` = 1 ";
my %options;
for my $p (qw'history onlyinc') {
   $options{$p}=param($p);
}
if($options{history}) {$wantcurrent=""}
if($options{onlyinc}) {$wantcurrent.=" AND status = 2 ";}

print AWheader($title);
print p(a({-href=>"?history=".(!$options{history})},"toggle history")." ".a({-href=>"?onlyinc=".(!$options{onlyinc})},"toggle incomings"));

print "sys#planet: info".br;

my ($allimatch,$amvars)=awinput::get_alli_match2($alli,1);
my $sth=$dbh->prepare_cached(
   "SELECT sidpid,sum(xcv),sum(trn),sum(cls) FROM `fleets`,toolsaccess 
   WHERE $allimatch AND `iscurrent` = 1 GROUP BY `sidpid` ");
my $res=$dbh->selectall_arrayref($sth, {}, @$amvars);

my @sidpids=sort {$$b[1]<=>$$a[1]} @$res;
my %cvsum;

foreach my $row1 (@sidpids) {
   my($sidpid,$sumcv,$trn,$cls)=@$row1;
   next if ($sumcv+$trn+$cls == 0);
   my $sid=awinput::sidpid2sidm($sidpid);
   my $pid=awinput::sidpid2pidm($sidpid);
   my $p="$sid#$pid";
   (my $penc=$p)=~s/#/%23/;
   my $planet=sidpid2planet($p);
   my $owner=planet2owner($planet);
   my $sb=planet2sb($planet);
   my @pinfo=getplanetinfo($sid,$pid);
	my $info=$pinfo[2]||"";
   if(!defined($sb)){$sb="?"}
   $info=~s!^\d [^ ]+!!;
   $info=~s!automagic:.*!!g;
	my $str=qq!<a href="planet-info?id=$penc">$p</a> of !.display_pid($owner)." SB $sb $info";
	#my $str=qq!<a href="system-info?id=$sid">$p</a> $info<br />\n!;

   my $res=awinput::get_fleets($sidpid, $wantcurrent);
   if(!$res || !@$res) {next}
   print "$str\n".br;
   foreach my $row2 (@$res) {
		my($owner,$cv, $xcv)=@$row2[4,13,14];
		$cvsum{$owner}+=$xcv;
      print awinput::show_fleet($row2).br;
   }
   print br;
}
print "<table><tr><th>Player</th><th>XCV</th></tr>";
foreach my $owner (sort {$cvsum{$b}<=>$cvsum{$a}} keys (%cvsum)) {
	print ("<tr>".td(playerid2link($owner)).td($cvsum{$owner})."</tr>");
}
print "</table>";
print AWtail();

