#!/usr/bin/perl -w

use strict;
use CGI ":standard";
BEGIN {chdir "/home/bernhard/code/cvs/perl/awcalc";}
use awstandard;
use awinput;
awinput_init();
my $title="fleets [\U$ENV{REMOTE_USER}\E]";
print AWheader($title);

our %CV;
my @out;

sub sortfunc { return $CV{$b}<=>$CV{$a} }

print "sys#planet: info".br;
foreach my $p (keys %planetinfo) {
	my $info=$planetinfo{$p};
	next unless $info=~s/$magicstring([^:]*)/$magicstring.span({-style=>"color: ".getrelationcolor((getrelation($1))[0])},$1)/geo;
	$info=~s/^.*?($magicstring)/$1/so;
	my @CV=($info=~/(\d+)CV/g);
	my $CV=0;
	foreach(@CV){$CV+=$_}
	if($CV==0 && $info=~/2005 (\d+) (\d+) (\d+) (\d+) (\d+)/) { $CV=fleet2cv([$1,$2,$3,$4,$5]); }
	$p=~/^(\d+)#/;
	my $sid=$1;
	(my $penc=$p)=~s/#/%23/;
   $info=~s!^!<br />!mg;
	my $str=qq!<a href="/cgi-bin/planet-info?id=$penc">$p</a> $info<br />\n!;
	#my $str=qq!<a href="/cgi-bin/system-info?id=$sid">$p</a> $info<br />\n!;
	push(@out,$str);
	$CV{$str}=$CV;
}
print (sort sortfunc @out);
print AWtail();
