#!/usr/bin/perl -w

use strict;
use CGI ":standard";
BEGIN {chdir "/home/aw/inc";}
use awstandard;
use awinput;
use DBAccess;
awinput_init();
my $alli=$ENV{REMOTE_USER};
my $title="fleets [\U$alli\E]";
my $wantcurrent=" AND `iscurrent` = 1 ";
my %options;
for my $p (qw'history') {
   $options{$p}=param($p);
}
if($options{history}) {$wantcurrent=""}


print AWheader($title);
print p(a({-href=>"?history=".(!$options{history})},"toggle history"));

print "sys#planet: info".br;

my $res=$dbh->selectall_arrayref("SELECT sidpid,sum(xcv),sum(trn),sum(cls) FROM `fleets` WHERE `alli` = '$alli' AND `iscurrent` = 1 GROUP BY `sidpid` ");


my @sidpids=sort {$$b[1]<=>$$a[1]} @$res;

foreach my $row1 (@sidpids) {
   my($sidpid,$sumcv,$trn,$cls)=@$row1;
   next if ($sumcv+$trn+$cls == 0);
   my $sid=awinput::sidpid2sidm($sidpid);
   my $pid=awinput::sidpid2pidm($sidpid);
   my $p="$sid#$pid";
   (my $penc=$p)=~s/#/%23/;
   my $planet=sidpid2planet($p);
   my $owner=planet2owner($planet);
   my $sb=planet2sb($planet);
	my $info=$planetinfo{$p};
   $info||="";
   $info=~s!^\d [^ ]+!!;
   $info=~s!automagic:.*!!g;
	my $str=qq!<a href="/cgi-bin/planet-info?id=$penc">$p</a> of !.display_pid($owner)." SB $sb $info";
	#my $str=qq!<a href="/cgi-bin/system-info?id=$sid">$p</a> $info<br />\n!;
   
   print "$str\n".br;

#   my $sth=$dbh->prepare_cached("SELECT * FROM `fleets` WHERE `alli` = ? $wantcurrent AND `sidpid` = ?");
   my $res=awinput::get_fleets($sidpid, $wantcurrent); #$dbh->selectall_arrayref($sth, {}, $alli, $sidpid);
   foreach my $row2 (@$res) {
      print awinput::show_fleet($row2).br;
      #print "@$row2\n".br;
   }
   print br;
}

print AWtail();

