#!/usr/bin/perl -w
use strict;
use CGI ":standard";
chdir "/home/bernhard/code/cvs/perl/awcalc";
require "standard.pm";
require "cgicommon.pm";

sub holesort { $$a[3]<=>$$b[3] || $$b[1]<=>$$a[2]}

print AWheader("holes list [\U$ENV{REMOTE_USER}\E]");

my $filename="holesdir/$ENV{REMOTE_USER}";
open(F, "<", $filename) or print "data not found";
my @holes=<F>;
close F;

my $mtime=gmtime((stat($filename))[9]);
print "Last Update $mtime GMT\n".br,
	"sys: members:friends:others".br;

foreach(@holes) { $_=[split(" ",$_)] }

foreach(sort holesort @holes) {
	my ($sid, $member, $friend, $other, $worstrel)=@$_;
	my $c=getrelationcolor($worstrel);
	print span({-style=>"color: $c"},"status ").a({href=>"system-info?id=$sid"},"$sid: $member:$friend:$other").br."\n";
}
print AWtail();
