#!/usr/bin/perl -w
# safe 070204
use strict;
use CGI ":standard";

use awstandard;
use awinput;
use sort_table;
awinput_init();

my %options;
for my $p (qw'sort') {
   $options{$p}=param($p);
}
if(!defined $options{sort}){$options{sort}="4.2";}

sub holesort { $$a[3]<=>$$b[3] || $$b[1]<=>$$a[2]}

print AWheader("holes list [\U$ENV{REMOTE_USER}\E]");

my $filename="$awstandard::allidir/$ENV{REMOTE_USER}/holes.csv";
if(not open(F, "<", $filename)) {
	print "data not found";
} else {
my @holes=<F>;
close F;

my $mtime=gmtime((stat($filename))[9]);
print "Last Update $mtime GMT\n".br;

foreach(@holes) { chop;$_=[split(/\t/,$_)] }

# calc system-worth
foreach my $h (@holes) {
   my $sid=$h->[0];
#   print $sid.br;
   my @p=systemid2planets($sid);
   my $sum=0;
   my $worth=0;
   foreach my $p (@p) {
      my $o=$p->{ownerid};
      my $tag=lc(playerid2tag($o));
      next if $tag ne $ENV{REMOTE_USER}; # skip non-members
      my $pop=$p->{pop};
      $sum+=$pop;
      $worth+=$pop-5;
   }
   push(@$h, $sum, $worth);
}

print sort_table([qw(system members friends others), "worst relation", "pop", "worth"],
      [\&display_sid, \&display_string, \&display_string, \&display_string, \&display_relation, \&display_string, \&display_string],
      [\&sort_num, \&sort_num, \&sort_num, \&sort_num, \&sort_num, \&sort_num, \&sort_num],
      sort_param_to_keys($options{sort}), \@holes);

print "<p><b>note: added sum of pop and sum of (pop-5) which is an approximation for the real worth of member's planets in a system</b>";
}
print AWtail();
