#!/usr/bin/perl -w
# safe 070204
use strict;
use CGI ":standard";
BEGIN {chdir "/home/aw/inc";}
use awstandard;
use awinput;
use sort_table;
awinput_init();

my %options;
for my $p (qw'sort') {
   $options{$p}=param($p);
}
if(!defined $options{sort}){$options{sort}="4.2";}

sub holesort { $$a[3]<=>$$b[3] || $$b[1]<=>$$a[2]}

print AWheader("holes list [\U$ENV{REMOTE_USER}\E]");

my $filename="/home/aw/alli/$ENV{REMOTE_USER}/holes.csv";
unless(open(F, "<", $filename)) {
	print "data not found";
	exit 0;
}
my @holes=<F>;
close F;

my $mtime=gmtime((stat($filename))[9]);
print "Last Update $mtime GMT\n".br;

foreach(@holes) { chop;$_=[split(/\t/,$_)] }

print sort_table([qw(system members friends others), "worst relation"],
      [\&display_sid, \&display_string, \&display_string, \&display_string, \&display_relation],
      [\&sort_num, \&sort_num, \&sort_num, \&sort_num, \&sort_num],
      sort_param_to_keys($options{sort}), \@holes);

print AWtail();
