#!/usr/bin/perl -w
use strict;
use CGI ":standard";
use Tie::DBI;
use Digest::MD5 "md5_hex";

use awstandard;
use awinput;
#awstandard_init();
awinput_init();
use DBAccess;
print AWheader("AW IP banning tool");


my %options;
my %ips;
tie %ips,'Tie::DBI',$dbh,'ipban','ip',{CLOBBER=>2};
my $pw=param("password");
#print "hash: ".md5_hex('saLtv'.$pw);
if($pw && md5_hex('saLtv'.$pw) eq '2067c9f2c32946c1cb7bf599550c5c86' ) {
	foreach my $p (qw(ip action reason)) {
		$options{$p}=param($p);
      $options{$p}=~s/[<>]//g;
	}
   my $ip=$options{ip};
   if($ip!~/^\d+\.\d+\.\d+\.\d+$/) {
      print "bad IP";
   } elsif($options{action} eq "add") {
      $ips{$ip}={timeadded=>time(), reason=>$options{reason}};
      print "added $ip";
   } elsif($options{action} eq "del") {
      delete $ips{$ip};
      print "deleted $ip";
   } else {
      print "error in request";
   }
} 

print start_form(-name=>"form"),textfield(-name=>'ip', -class=>'text')," IP",br,
      textfield(-name=>'reason', -class=>'text'), " reason",br,
      password_field(-name=>'password', -class=>'text'), " password",br,
      popup_menu(-name=>'action', -values=>["add","del"]), " action",br,
   submit(-name=>"ban IP", -class=>'smbutton'),end_form.AWfocus("form.ip");
print br.q'<div style="border: solid white 1px;">';
foreach my $ip (keys %ips) {
   my $l=a({-href=>"?ip=$ip&action=del&password=$pw"},"un-ban");
   print $l." $ip added ".(scalar localtime $ips{$ip}->{timeadded})." reason: ".$ips{$ip}->{reason}.br;
}
untie %ips;
print "</div>";
print AWtail();

