#!/usr/bin/perl -w
use strict;
use CGI ":standard";
BEGIN {chdir "/home/aw/db"}
use awinput;
print header();
use WWW::Mechanize;
#use WWW::Mechanize::FormFiller;
#use URI::URL;


my $uri1='http://www.astrowars.com/forums/';
my $agent = WWW::Mechanize->new( autocheck => 1 );
#my $formfiller = WWW::Mechanize::FormFiller->new();
$agent->env_proxy();

  $agent->get($uri1);
#    $agent->form(1) if $agent->forms and scalar @{$agent->forms};
  $_=$agent->content;
  /The newest registered user is <b><a href="[^"]*u=(\d+)([^"]*)"/;
  my $pid=$1;
  $agent->get("http://www1.astrowars.com/about/playerprofile.php?id=$pid");
#  $agent->follow(qr((?-xism:Public)));
  $_=$agent->content;
  m!<html><head><title>([^ ]*)!;
  my $name=$1;
  m!<a href ="/about/starmap.php\?dx=([+-]?\d+)&dy=([+-]?\d+)"!;
  my ($x,$y)=($1,$2);
  my $time = gmtime();
  awinput_init();
  my $sid=systemcoord2id($x,$y);
  awinput::awinput_finish();
  print "$time $sid $pid $name ",
      "($x,$y)\n";

