#!/usr/bin/perl -w
use strict;
use CGI ":standard";
use LWP::Simple ("get");

use awstandard;
use awinput;
awstandard_init();
#awinput_init();

print AWheader("AW inofficial login position tool"),
 "This tool uses the forum's \"The newest registered user is\"-info to find out:",br,br;

my $uri1='http://www.astrowars.com/forums/';
  $_=get("$uri1");
  /The newest registered user is <b><a href="[^"]*u=(\d+)([^"]*)"/;
  my $pid=$1;
  $_=get("http://www1.astrowars.com/about/playerprofile.php?id=$pid");
  m!<html><head><title>([^ ]*)!;
  my $name=$1;
  m!<a href ="/about/starmap.php\?dx=([+-]?\d+)&dy=([+-]?\d+)"!;
  my ($x,$y)=($1,$2);
  my $time = gmtime();
  awinput_init();
  my $sid=systemcoord2id($x,$y);
  awinput::awinput_finish();
  print "$time sid=$sid pid=$pid $name ",
      "($x,$y)\n";

print AWtail;
