#!/usr/bin/perl -w
# safe 070204
use strict;
use CGI ":standard";


use awstandard;
use awinput;
awstandard_init();
#awinput_init();

our %options;
print AWheader("Change [\U$ENV{REMOTE_USER}\E] AWtools password");
if(param()) {
	foreach my $p (qw(p)) {
		$options{$p}=param($p);
	}
   my $p=$options{p};
   if($p=~m/^[a-zA-Z0-9,.:\/=%+_-]{4,8}$/ && $ENV{REMOTE_USER} ne "guest") {
      use http_auth;
      setdbpasswd($p);
      system(qw(/usr/bin/htpasswd -b), "$awstandard::codedir/.htpasswd", $ENV{REMOTE_USER}, $p);
      if ($? == -1) {
         print "failed to change password. Ask the tools admin to check.";
      } else {
         print "OK.";
      }
   } else {
      print "password not changed. should be 4-8 chars, excluding some special chars"
   }
} else {
	print "Be careful with this one. Do not forget your new password.",
      start_form(-name=>"form"),textfield(-name=>'p', -class=>'text')," new password (4-8 characters)",br,
		submit(-name=>"query", -class=>'smbutton'),end_form.AWfocus("form.p");
}
print AWtail();

