#!/usr/bin/perl -w
# safe 070204
use strict;
use CGI ":standard";


use awstandard;
use awinput;
use http_auth;
awstandard_init();
#awinput_init();

our %options;
print AWheader("Change [\U$ENV{REMOTE_USER}\E] AWtools password");
my @pass=getdbpasswd($ENV{REMOTE_USER});
my $pwhash=$pass[1];

if(param()) {
	foreach my $p (qw(p)) {
		$options{$p}=param($p);
	}
   my $p=$options{p};
   if((!$pwhash || (param("oldpw") eq $pwhash)) && $p=~m/^[a-zA-Z0-9,.:\/=%+_-]{4,48}$/ && $ENV{REMOTE_USER} ne "guest") {
      my $r=setdbpasswd($p);
      system(qw(/usr/bin/htpasswd -m -b), "$awstandard::codedir/.htpasswd", $ENV{REMOTE_USER}, $p);
      if (!$r || $? == -1) {
         print "failed to change password. Ask the tools admin to check.";
      } else {
         print "OK.";
      }
   } else {
      print "password not changed. should be at least 4 chars, excluding some special chars"
   }
} else {
	param('oldpw', $pwhash);
	print "Be careful with this one. Do not forget your new password.",
      start_form(-name=>"form"),
		hidden(-name=>'oldpw'),
		textfield(-name=>'p', -class=>'text')," new password (4-8 characters)",br,
		submit(-name=>"query", -class=>'smbutton'),end_form.AWfocus("form.p");
}
print AWtail();

