#!/usr/bin/perl -w
use strict;
use CGI ":standard";

my $title="manage planet info";
my %options;
chdir "/home/bernhard/code/cvs/perl/awcalc";
require "input.pm";
require "cgicommon.pm";

print AWheader($title);
for my $p (qw'id status who comment legend submit') {
	$options{$p}=param($p);
}
if(param("legend")) {
        print "legend: "; 
        for my $n (1..7) {
                my $color=getstatuscolor($n);
                print span({-style=>'color: '.$color}, br."$n $color = $::planetstatusstring{$n}\n");
        }
        print end_html;
        exit 0; 
}


if($options{status}) {
	$options{status}+=0;
	if($options{status}<1 || $options{status}>9) { print "wrong input"; exit 0;}
	if($options{who}=~/[a-zA-Z ]/) {
		$options{who}=playername2id($options{who});
	}
	if(!$options{who}) {$options{who}=2};
	if($options{id}!~m/(\d+)#(\d+)/) {print "invalid system/planet id\n"; exit 0; }
	my ($sid,$pid)=($1,$2);
	my @pinfo=getplanetinfo($sid,$pid,1);
	my $mod=(@pinfo)? "modified" : "added";
	if($options{submit}=~/delete/) {
		setplanetinfo($pinfo[3],undef);
		$mod="deleted";
	} else {
		#$options{info}=$options{comment};
		setplanetinfo($pinfo[3],{"sidpid"=>sidpid22sidpid3($sid,$pid), "status"=>$options{status}, "who"=>$options{who}, "info"=>$options{comment}});
	}
	print span({-style=>'color: darkgreen'},"$mod $options{id}"),br;
}

if($options{id}) {
	my $id=$options{id};
	if($id!~m/(\d+)#(\d+)/) {print "invalid system/planet id\n"; exit 0; }
	my ($sid,$pid)=($1,$2);
	my @pinfo=getplanetinfo($sid,$pid);
	print qq!<a href="?legend=1">legend</a>!,br;
	my $new="edit existing entry";
	my $link="";
	if(!@pinfo) {
		$options{status}=1;
		$options{who}=2;
		$options{comment}="";
		$new=span({-style=>'color: red'},"add new entry");
	} else {
		($options{status},$options{who},$options{comment})=@pinfo;
		my $name=playerid2name($options{who});
		$link=qq! - <a href="relations?name=$name">info on $name</a>!;
	}

	print start_form, "$new: ". span({-style=>'color: '.getstatuscolor($options{status})},systemid2name($sid)."($id)")." ", systemlink($sid), br,
		popup_menu(-name=>'status', -values=>[1..7], -default=>$options{status},
		-labels=>\%::planetstatusstring), " status", br,
		textfield(-name=>'who', -value=>$options{who}, -class=>'text'), " user-id or user-name of the one who does the above $link", br,
		textarea(-name=>'comment', -value=>$options{comment}, -rows=>9, -cols=>40, -class=>'text'), " ETA, fleet, etc...", br,
		hidden(-name=>'id', $id),
		submit(-name=>"submit", -class=>'smbutton'), qq! <a href="?">new query</a> !, submit(-name=>"submit",-value=>"delete entry", -class=>'smbutton');
} else {
	print start_form('get'), textfield(-name=>'id', -class=>'text'), " ID: system#planet", br,
	 submit(-name=>"query", -class=>'smbutton')
}
print end_form, end_html;
