#!/usr/bin/perl -w
use strict;
use CGI ":standard";


use awstandard;
use awinput;
use awlogins;
#awstandard_init();
awinput_init(1);

our $ticks=3; # chars per hour - must be positive integer
our $granularity=24*$ticks;
my $unk="?";
my %cmap=($unk=>"gray", X=>"green", "-"=>"red");

our $firstlog=0;
my $firstlogt;
sub time2dt($) { my($time)=@_;
      my($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = gmtime($time);
		return int($time/awstandard::DAYSECS*$granularity - $firstlog);
}

my %options;
print AWheader("AW player idle time viewer");
print start_form(-name=>"form",-method=>"get"),textfield(-name=>'name', -class=>'text')," player name",br,
   submit(-name=>"query", -class=>'smbutton'),end_form.AWfocus("form.name");
if(param()) {
	foreach my $p (qw(name)) {
		$options{$p}=param($p);
	}
   if(my $id=playername2idm($options{name}))
   {
      my @logins=@{awlogins::get_logins($ENV{REMOTE_USER}, $id)};
      my @logs;
      my $lastlog=-1;
      my $lastlogn=-1;
      foreach (@logins) {
         my @l=@$_;
         my $dt1=time2dt($l[1]-$l[3]);
         if(!$firstlog) {$firstlogt=$l[1]-$l[3];$firstlog=$dt1-$dt1%$granularity; $dt1-=$firstlog;}
         my $dt=time2dt($l[1]);
         my $dt2=time2dt($l[1]+$l[2]);
         next if($dt1<0 || $dt<0 || $dt2<0);
         for my $dti ($lastlog+1..$dt1-1) { $logs[$dti]=($lastlogn+1==$l[0] ?"-":$unk); }
         for my $dti ($dt1..$dt) { $logs[$dti]="X"; }
         for my $dti ($dt+1..$dt2) { $logs[$dti]="-"; }
         $lastlog=$dt2;
         $lastlogn=$l[0];
#      print "@l $dt $dt1 $dt2<br>";
      }
      my $n=0;
      print "player: ".playerid2link(playername2id($options{name})),br,br,
            a({href=>"playeronline2?name=$options{name}"}, "probability graph"),br,br,
            "<code>legend: ",br,
            "'X': logged in",br,
            "'-': idle (or sometimes permanently logged in)",br,
            "'$unk': unknown status",br,
            "all times in UTC - current time: ".gmtime(),br,
            "</code><pre>  day\\hour";
#"0 1 2 3 4 5 6 7 8 9 1011121314151617181920212223";
      for(0..23) {printf("%${ticks}i", $_);}
      my $currt=$firstlogt;
      foreach(@logs) {
         if($n++%$granularity==0) {
            my $wday=(gmtime($currt))[6];
            my $s1="";
            my $s2="";
            if($wday==6||$wday==0) {
               $s1="<span style=\"background-color:gray\">";
               $s2="</span>";
            }
            print br,$s1,AWisodate($currt),$s2," ";
            $currt+=3600*24;
         }
         print "<span style=\"color:$cmap{$_}\">$_</span>";
      }
      print "</pre>";
   }
}
print "Note: for AW premium members, the green X only mean <i>'might have been online during that period'</i>... just the same as for non-premiums but login times are much less known for premiums\n";
print AWtail();

