#!/usr/bin/perl -w
use strict;
use CGI ":standard";
BEGIN {chdir "/home/aw/inc";}
use awstandard;
$style=cookie('style');

my $u=param('user');
my $uc=cookie('user');
my $ref=param('ref');
my $refc=cookie('refsys');
my $stylep=param('style');
my $stylec=cookie('style');
my $tz=param('tz');
my $tzc=cookie('tz');
if($stylep) {$style=$stylep}

if(!defined($u) && $uc) {param("user",$uc);$u=$uc}
if(!defined($ref) && $refc) {param("ref",$refc);$ref=$refc}
if(!defined($stylep) && $stylec) {param("style",$stylec);$stylep=$stylec}
if(!defined($tz) && $tzc) {param("tz",$tzc);$tz=$tzc}
if(!defined($tz)) {param("tz",2)}
if(defined($u)) {
   $ref||="";
   my @cookies;
	push(@cookies, cookie(-name=>'user', -value=>$u, -expires=>'+90d'));
	push(@cookies, cookie(-name=>'refsys', -value=>$ref, -expires=>'+90d'));
	push(@cookies, cookie(-name=>'style', -value=>$stylep, -expires=>'+600d'));
	push(@cookies, cookie(-name=>'tz', -value=>$tz, -expires=>'+600d'));
	print header(-cookie=>\@cookies).AWheader2("logged in as $u ($ref)");
} else { print AWheader("login"); }

print start_form(-method=>'get', -name=>"form"), textfield(-name=>'user', -class=>'text'), " user name", br.AWfocus("form.user"),
textfield(-name=>'ref', -class=>'text'), " sys#planet (used for ETA calculation - e.g. 1#1 for Rana 1)", br,
popup_menu(-name=>'style', -values=>[qw(green blue aw plain)]), " color theme for AWtools", br,
popup_menu(-name=>'tz', -values=>[-11..12]), " timezone for AWtools", br,
submit(-name=>"submit", -class=>'smbutton'), end_form, br,
   "This tool sets cookies which are stored in your browser and used by some of my other tools.",
end_html;

