#!/usr/bin/perl -w
use strict;
use CGI ":standard";
chdir "/home/bernhard/code/cvs/perl/awcalc";
require "standard.pm";

my $u=param('user');
my $uc=cookie('user');
my $ref=param('ref');
my $refc=cookie('refsys');

if(!defined($u) && $uc) {param("user",$uc);$u=$uc}
if(!defined($ref) && $refc) {param("ref",$refc);$ref=$refc}
if(defined($u)) {
	my $cookie=cookie(-name=>'user', -value=>$u, -expires=>'+90d');
	my $cookie2=cookie(-name=>'refsys', -value=>$ref, -expires=>'+90d');
	print header(-cookie=>[$cookie,$cookie2]).AWheader2("logged in as $u ($ref)");
} else { print AWheader("login"); }

print start_form('get'), textfield(-name=>'user', -class=>'text'), " user name", br,
textfield(-name=>'ref', -class=>'text'), " sys#planet (used for ETA calculation - e.g. 1#1 for Rana 1)", br,
submit(-name=>"submit", -class=>'smbutton'), end_form, "",
end_html;

