#!/usr/bin/perl -w
use strict;
use CGI ":standard";

use awstandard;
use awinput;
awstandard_init();
#awinput_init();

our %options;
print AWheader("AW race creation link tool");
if(param()) {
   my @p;
   foreach(qw(name pw)) {
      my $x=param($_);
      $x=~s/[<>]//g;

      if($_ eq "name") { # autodetect PID
         my $id=playername2idm($x)||"???";
         $x=playerid2namem($id);
         push(@p, "id=$id");
      }
      push(@p,"$_=$x");
   }
   {
      my @a=param("auswahl[]");
      my $raceid=0;
      foreach(@a) { $raceid+=$_ }
      push(@p, "raceid=$raceid");
   }
   foreach(qw(growth science culture produktion speed attack defense)) {
      my $x=param($_);
      $x=~s/[^0-9+-]//g;
      push(@p,"$_=$x");
   }
   print "http://www1.astrowars.com/register/start.php?".join("&",@p);
   print br,"Beware: this link will sign you into AW immediately upon clicking";
} else {
   print "no input. ".a({-href=>"/customize_race.html"},"use this page")." to select your race".br;
}
print AWtail();

