#!/usr/bin/perl -w
use strict;
use CGI ":standard";
use DB_File;

my $title="add relation";
my $dbname="/home/bernhard/db/$ENV{REMOTE_USER}-relation.dbm";
my %options;
print header, start_html($title), h1($title);
for my $p (qw'user alliance relation comment') {
	$options{$p}=param($p);
}
if($options{relation}) {
	$options{user} =~ y/A-Z/a-z/;
	$options{alliance} =~ y/a-z/A-Z/;
	my %data;
	tie(%data, "DB_File", $dbname) or print "error accessing DB\n";
	$options{user}=~s/[\r\n\t ]+/ /g;
	my $i=0;
	foreach my $user(split(" ", $options{user})) {
		$i++; print "user $i: $user\n<br>";
		if($user=~m/^\s*$/) {next}
		if($user !~ /^[-_. a-z0-9\[\]]*$/) { print 'illegal character in user name'; exit(0);}
		$options{relation}+=0;
		if($options{relation}<1 || $options{relation}>9 || $options{alliance} !~ /^[A-Z]*$/) { print "wrong input"; exit 0;}
		if($options{alliance}=~/^\s*$/) {$options{alliance}="unknown"}
		$data{$user}="$options{relation} $options{alliance} $options{comment}";
	}
	untie(%data);
	print span({-style=>'color: darkgreen'},"added $options{user}"),br;
}

if(1) {
	$options{alliance}="unknown";
	$options{comment}="";
	$options{relation}=4;
	
	print start_form, "enter one on each line", br;
	print textarea(-name=>'user', "all\nmembers"), br;
	print textfield('alliance', $options{alliance}), " alliance membership (e.g. unknown, TZAR, ES)", br,
	popup_menu(-name=>'relation', -values=>[1..9], -default=>$options{relation},
		-labels=>{1=>"total war", 2=>"foe", 3=>"tense", 4=>"unknown(neutral)", 5=>"implicit neutral", 6=>"NAP", 7=>"friend", 8=>"ally", 9=>"member"}), " relation", br,
	textarea('comment', $options{comment}), " who added him, why, contact etc...", br,
	submit("submit all - really sure?")
} 
else {
	print start_form('get'), textfield(-name=>'user'), " user name", br,
	 submit("query")
}
print end_form, end_html;
#foreach(keys %ENV) {  print "$_ $ENV{$_}<br>";}

