#!/usr/bin/perl -w
# should be safe 070205
use strict;
use CGI ":standard";
use DB_File;

BEGIN {chdir "/home/aw/inc";}
use awstandard;
use awinput;
awinput_init();

my $title="add relation";
my $dbname="/home/bernhard/db/$ENV{REMOTE_USER}-relation.dbm";
my %options;
print AWheader($title);
for my $p (qw'user alliance relation comment') {
	$options{$p}=param($p);
}
if(defined($options{relation})) {
   if($options{comment}) {
      $options{comment} =~ s/[<>]//g;
   }
	$options{user} =~ y/A-Z/a-z/;
	if($options{alliance}=~/^\s*$/) {$options{alliance}="unknown"}
	$options{alliance} =~ y/a-z/A-Z/;
	my %data;
	tie(%data, "DB_File", $dbname) or print "error accessing DB\n";
	$options{user}=~s/[\r\n\t ]+/ /g;
	my $i=0;
	foreach my $user(split(" ", $options{user})) {
      my $pid=playername2id($user);
      if(!$pid) {print "skipped ".safe_encode($options{user});next}
		$i++; print "user $i: ".playerid2link($pid).br;#a({-href=>"relations?name=$user"},$user).br;
		if($user=~m/^\s*$/) {next}
#		if($user !~ /^[-_. a-z0-9\[\]]*$/) { print 'illegal character in user name'; exit(0);}
		$options{relation}+=0;
		if($options{relation}<0 || $options{relation}>9 || $options{alliance} !~ /^[A-Z]*$/) { print "wrong input"; exit 0;}
		my @rel=getrelation($user);
      $rel[2]||="";
		$data{$user}="$options{relation} $options{alliance} $options{comment}\n$rel[2]";
	}
	untie(%data);
	print span({-style=>'color: darkgreen'},"added $options{user}"),br;
}

if(1) {
	$options{alliance}="unknown";
	$options{comment}="";
	$options{relation}=0;
	
	print start_form, "enter one on each line", br;
	print textarea(-name=>'user', "all\nmembers"), br;
	print textfield(-name=>'alliance', -value=>$options{alliance}, -class=>'text'), " alliance membership (e.g. unknown, TZAR, ES)", br,
	popup_menu(-name=>'relation', -values=>[0..9], -default=>$options{relation},
		-labels=>\%::relationname), " relation", br,
	textarea('comment', $options{comment}), " who added him, why, contact etc... (will be prepended)", br,
	submit(-name=>"submit all - really sure?", -class=>'smbutton')
} 
else {
	print start_form('get'), textfield(-name=>'user'), " user name", br,
	 submit("query")
}
print end_form, end_html;

