#!/usr/bin/perl -w
use strict;
use CGI ":standard";
chdir "/home/bernhard/code/cvs/perl/awcalc";
require "standard.pm";

my $title="AW economic simulation";
print AWheader($title);
my @params=();
foreach(qw(turns print tactic pop pp cul sci social initialp)) { if(param($_)) {push(@params, "--$_=".param($_));}}
if(@params && param("turns")<=9999) {
	print "simulating...".br."\n<pre>";
	system("./awsim.pl", @params);# or print "failed executing\n";
	print "</pre>\n";
} else {
	my @default=(7300,7300,4);
#	my @default=(400,40,3);
	print start_form('get'), 
	textfield(-name=>'turns', -value=>$default[0], -class=>'text'), " how many turns (of 15 min) to simulate", br,
	textfield(-name=>'print', -value=>$default[1], -class=>'text'), " print only each n turns", br,
	textfield(-name=>'tactic', -value=>$default[2], -class=>'text'), " use tactic (1..5)", p,
	textfield(-name=>'pop', -value=>0, -class=>'text'), " growth bonus (-4..+4)", br,
	textfield(-name=>'sci', -value=>0, -class=>'text'), " science bonus", br,
	textfield(-name=>'cul', -value=>0, -class=>'text'), " culture bonus", br,
	textfield(-name=>'pp', -value=>0, -class=>'text'), " production bonus", br,
	textfield(-name=>'social', -value=>0.3, -class=>'text'), " how much to put in social science ", br,
	textfield(-name=>'initialp', -value=>120, -class=>'text'), " initial starting points", br,
	submit(-class=>'smbutton'), end_form, 
}
print end_html;

