#!/usr/bin/perl

use strict;
use CGI ":standard";

my %options;

sub spinfo($) { my($id)=@_; # short player info string
	if($id==2) {return "unknown"}
	if($id==0) {return "free planet"}
	my $name=$::player{$id}{name};
	my $aid=$::player{$id}{alliance};
	my @rel=getrelation($name);
	my $color=getrelationcolor($rel[0]);
	my $alliancestr="";
	if(!$rel[1] && $aid>0) { $rel[1]=$::alliances{$aid}{tag} }
	if($rel[1]) { $alliancestr="[".$rel[1]."]"; }
	my $rellink=qq! <a href="relations?name=$name"><img src="/images/aw/relations-colored.gif" title="player info + relation"></a> !;
	return profilelink($id).$rellink.
		span({-style=>'color: '.$color}, qq!$alliancestr $name ($id) !);
}

my $path="/home/bernhard/code/cvs/perl/awcalc";
chdir $path;
for my $p (qw'x y') {
  $options{$p}=param($p);
}
if(defined($options{x}) && defined($options{y})) {
	require "awmap.pm";
	my($x,$y)=imgtomap($options{x}, $options{y});
	print redirect("http://$ENV{HTTP_HOST}$ENV{SCRIPT_NAME}?mapx=$x&mapy=$y");
	exit(0);
}
print header;
print start_html('AW system info');

if(param("legend")) {
	require "input.pm";
	print "legend: ";
	for my $n (1..9) {
		my $color=getrelationcolor($n);
		print span({-style=>'color: '.$color}, br."$n $color = $::relationname{$n}\n");
	}
	print end_html;
	exit 0;
}

if(param()) {
	my($x,$y,$system);
	for my $p (qw'x y mapx mapy id name') {
	  $options{$p}=param($p);
	}
	require "awmap.pm";
	require "input.pm";
	if(defined($options{mapx})) { ($x,$y)=($options{mapx}, $options{mapy}) }
	elsif(defined($options{x})) { ($x,$y)=imgtomap($options{x}, $options{y}) }
	if(defined($x)) { $system=systemcoord2id($x,$y) }
	if(!$system && $options{name}) { $system=systemname2id($options{name}) }
	if(!$system && $options{id}) { $system=$options{id} }
	if(!$system) {
		print "no system $options{name} at $x,$y";
	} else {
		($x,$y)=($::starmap{$system}{x},$::starmap{$system}{y});

		## start of normal output ##
		print qq!<a href="?legend=1">legend</a> <a href="?">new query</a>!,br;
		print "<b>$::starmap{$system}{name}($x,$y)</b><br>Id=$system level=$::starmap{$system}{level}",
		qq! <a href="tactical-large?xs=$x&ys=$y&xe=27&ye=17">tactical</a> <a href="http://www1.astrowars.com/about/starmap.php?dx=$x&dy=$y">starmap</a> <a href="http://www1.astrowars.com/0/Map/Detail.php/?nr=$system">map/details</a>!,br;
		print "planets here: <ul>";
		my $planets=$::planets{$system};
		foreach my $h (@$planets) {
			print li;
			next if(!$h);
#			foreach my $item (sort keys %$h) { print " $item=$$h{$item}\n"; }
			my $id="$system#$$h{planetid}";
			my $pinfo;
			my @pinfo=getplanetinfo($system,$$h{planetid});
			$id=~s/#/%23/;
			my $info="";
			if(@pinfo) {
				my $status=$pinfo[0];
				my $name=playerid2name($pinfo[1]);
				$pinfo=$pinfo[2];
				my @rel=getrelation($name);
				$info=" ".span({-style=>'color: '.getstatuscolor($status)},$::planetstatusstring{$status})." ".span({-style=>'color: '.getrelationcolor($rel[0])},getatag($rel[1])." ".$name).": ".$pinfo;
			}
			my $plink=qq! <a href="planet-info?id=$id"><img src="/images/aw/edit-planet.gif" title="edit planet-info"></a> !;
			my $siegedcol="";
			if(planet2siege($h)) { $siegedcol=qq!style="background-color: red"!; }
			printf "<span $siegedcol><code>#%2i pop=%2i SB=%2i</code></span> %s%s%s", $$h{planetid}, planet2pop($h), planet2sb($h), $plink, spinfo($$h{ownerid}), $info;
			
		}
		print "</ul>\n";
		print "players having their origin here: <ul>";
		foreach(@{$::starmap{$system}{origin}}) { print li,spinfo($_); }
		print "</ul>\n";
	}
} else { 
  print start_form('get'),
   textfield('mapx'), " x", br,
   textfield('mapy'), " y (e.g. x=0 y=0 for Rana)", br,
   "or",br,
   textfield('id'), " system id", br,
   "or",br,
   textfield('name'), " system name", br,
   submit, end_form;
}
print end_html;

