#!/usr/bin/perl -w
use strict;
use mod_perl;
use constant MP2 => ($mod_perl::VERSION >= 1.99);
use Apache::RequestRec ();
chdir "/home/aw/db/large-$ENV{REMOTE_USER}";
my ($x,$y)=$ENV{QUERY_STRING}=~m/x=([^=]*)&y=([^=]*)/;
my $f="star$x,$y.png";
my ($size,$modified)=(stat($f))[7,9];
open(F,"<", $f) or die $!;
undef($/);
my $image=<F>;

my $r = shift;
   $r->content_type('image/png');
   $r->set_content_length($size);
   $r->set_keepalive();
   $r->headers_out->set("max-age"=>3600);
   $r->set_last_modified($modified);
   $r->print($image);

