#!/usr/bin/perl
use strict;
use CGI ":standard";

if(!$ENV{REMOTE_USER}) {$ENV{REMOTE_USER}="af"}
my $title="tactical map [\U$ENV{REMOTE_USER}\E]";
my %options;
chdir "/home/bernhard/code/cvs/perl/awcalc";
#require "standard.pm";
require "awmap.pm";

for my $p (qw'map') {
	$options{$p}=param($p);
}
if($options{map}) {
	my $f="tactical-$ENV{REMOTE_USER}.png";
	open(F, "< $f") or die $!;
	my $size=(stat($f))[7];
	my $modified=(stat(_))[9];
	print header(-type=>'image/png', -expires=>"+6h", -last_modified=>$modified, -content_lenth=>$size);
	print <F>;
} else {
	print header(-expires=>'+1d'), 
		start_html(-title=>$title , -style=>"/tactical.css"), 
		#AWheader2($title),
		start_form('get', "coord"),
		qq!<input type="image" src="?map=1" />!,
qq%<script language="JavaScript1.2" type="text/javascript">
<!--
var IE = document.all?true:false
if (!IE) document.captureEvents(Event.MOUSEMOVE)
document.onmousemove = getMouseXY;
var tempX = 0
var tempY = 0
function getMouseXY(e) {
  if (IE) {
    tempX = event.clientX + document.body.scrollLeft
    tempY = event.clientY + document.body.scrollTop
  } else {
    tempX = e.pageX
    tempY = e.pageY
  }
  window.status="("+Math.floor((tempX-0)/$::pixelpersystem+($::mapxoff))+","+Math.floor((tempY-0)/$::pixelpersystem+($::mapyoff))+")"
  return true
}
//--></script>%;
	print end_form, end_html;
}

