#!/usr/bin/perl
# safe 070205
use strict;
use CGI ":standard";

BEGIN {chdir "/home/aw/inc";}
use awstandard;
use awinput;
#use awmap;
use awmapcgi;
awstandard_init();

sub round($) {int($_[0]+0.5)}
my $alli=$ENV{REMOTE_USER};
#if(!$ENV{REMOTE_USER}) {$ENV{REMOTE_USER}="af"}
my $title="large tactical map [\U$alli\E]";
my %options;

#chdir "large-$alli";
my $dir="/home/aw/alli/$alli/l";
for my $p (qw'xs xe ys ye x y fast scale') {
	$options{$p}=param($p);
   $options{$p}=~s/[^-+0-9.]//g; # sanitize user input
}
if(!$options{scale} || $options{scale}!~m/^[0-9.]+$/) { $options{scale}=2; }
my $imgsize=$options{scale}*13;

if(defined($options{x}) && defined($options{y})) {
	my $f="$dir/star$options{x},$options{y}.png";
	my $size=(stat($f))[7];
	my $modified=(stat($f))[9];
	print header(-type=>'image/png', -expires=>'+3h', -last_modified=>awstandard::HTTPdate($modified), -content_lenth=>$size);#, Connection=>"keep-alive", Keep_Alive=>300);
	undef($/);
	open(F,"< $f") or die $!;
	print <F>;
	exit(0); # modperl OK
}

if(defined($options{xs}) && !($options{xe}<0 || $options{ye}<0 || $options{xe}>100 || $options{ye}>100))
{
   print AWheader($title, qq(<style type="text/css"><!-- img {border:0;} --></style>));
	my $xe=round($options{xs}+$options{xe}/2);
	my $ye=round($options{ys}+$options{ye}/2);
	my $xs=$xe-$options{xe};
	my $ys=$ye-$options{ye};
	print qq!<table border="0" cellspacing="0" cellpadding="0" bgcolor='#000000'>!;
	for(my $my=$ys; $my<$ye; $my++) {
		print "<tr>";
		for(my $mx=$xs; $mx<$xe; $mx++) {
#			print "<td> $mx,$my</td>"
			my $f="$dir/star$mx,$my.png";
			my $link="";
			my $linkend="</a>";
			if(! -e $f) {my $n=0;
				if($mx%10<=1) {$n|=2}
				if($my%10<=1) {$n|=1}
				if($mx%10==0||$my%10==0) {$n=3}
				$f="/$n.gif";
				$link=qq!<a href="?xs=$mx&amp;ys=$my&amp;xe=$options{xe}&amp;ye=$options{ye}&amp;fast=$options{fast}&amp;scale=$options{scale}">!;
			} else {
#				$f="?x=$mx&amp;y=$my";
				$f="/alli/$alli/l/star$mx,$my.png";
            if($options{fast}==1) {
               $f="/cgi-bin/nphperl/tactical-large-tile?x=$mx&amp;y=$my";
               #$f="http://aw.lsmod.de:2349/tactical-large.pl?x=$mx&y=$my";
            } elsif($options{fast}==2) {
               $f="?x=$mx&amp;y=$my";
            }
				$link=qq!<a href="system-info?mapx=$mx&amp;mapy=$my">!;}
			my $formatstr="";
			if(1 || $my==$ys || $mx==$xs) {$formatstr=qq! height="$imgsize" width="$imgsize"!}
			print qq!<td>$link<img src="$f"$formatstr alt="" />$linkend</td>!;
		}
		print "</tr>\n";
	}
	print "</table>";
} else {
   awinput_init();
	print header(), AWheader2($title);
	print start_form(-method=>'get', -name=>"form"), 
    awmapcgi::awmapcoordinput(),
    checkbox(-name=>'fast', -label=>'fast', -checked=>1, -value=>'1'), " - uncheck when images are missing",br,
    popup_menu(-name=>'scale',-values=>[1,1.5,2,2.5,3,4], -default=>2)," scaling factor",br,
	 submit(-name=>"draw", -class=>'smbutton'), end_form();
   awinput::awinput_finish();
}
print end_html;
