#!/usr/bin/perl
use strict;
use CGI ":standard";

use awstandard;
use awmap;
awstandard_init();

my $alli=$ENV{REMOTE_USER};
#if(!$alli) {$alli="af"}
my $title="tactical map [\U$alli\E]";
my %options;

for my $p (qw'map') {
	$options{$p}=param($p);
}
if($options{map}) {
	my $f="$awstandard::allidir/$alli/tactical.png";
	my ($size,$modified)=(stat($f))[7,9];
	open(F, "<", $f) or die $!;
	print header(-type=>'image/png', -last_modified=>awstandard::HTTPdate($modified), -expires=>"+2h", #-last_modified=>$modified,
    -content_lenth=>$size);
   local $/;
   print <F>;
} else {
	print header(-expires=>'+1d'), 
		start_html(-title=>$title , -style=>"/code/css/tools/tactical.css"), 
		#AWheader2($title),
		start_form('get', "coord"),
		qq!<input type="image" src="?map=1" />!,
qq%<script language="JavaScript1.2" type="text/javascript">
<!--
var IE = document.all?true:false
if (!IE) document.captureEvents(Event.MOUSEMOVE)
document.onmousemove = getMouseXY;
var tempX = 0
var tempY = 0
function getMouseXY(e) {
  if (IE) {
    tempX = event.clientX + document.body.scrollLeft
    tempY = event.clientY + document.body.scrollTop
  } else {
    tempX = e.pageX
    tempY = e.pageY
  }
  window.status="("+Math.floor((tempX-0)/$pixelpersystem+($mapxoff))+","+Math.floor((tempY-0)/$pixelpersystem+($mapyoff))+")"
  return true
}
//--></script>%;
	print end_form, end_html;
}

