#!/usr/bin/perl
use strict;
use CGI ":standard";
alarm 30;

my $imgsize=2*13;
sub round($) {int($_[0]+0.5)}
if(!$ENV{REMOTE_USER}) {$ENV{REMOTE_USER}="af"}
my $title="large tactical map [\U$ENV{REMOTE_USER}\E]";
my %options;
chdir "/home/bernhard/code/cvs/perl/awcalc";
require "awmap.pm";
require "awmapcgi.pm";
#require "input.pm";
require "cgicommon.pm";

chdir "large-$ENV{REMOTE_USER}";
for my $p (qw'xs xe ys ye x y fast') {
	$options{$p}=param($p);
}
if(defined($options{x}) && defined($options{y})) {
	my $f="star$options{x},$options{y}.png";
	my $size=(stat($f))[7];
	my $modified=(stat($f))[9];
   my($sec,$min,$hour,$mday,$mon,$year,$wday,$yday)=gmtime($modified);
   $year+=1900;
   $modified=sprintf("$::weekday[$wday], %.2i $::month[$mon] $year %.2i:%.2i:%.2i GMT", $mday, $hour, $min, $sec);
	print header(-type=>'image/png', -expires=>'+3h', -last_modified=>$modified, -content_lenth=>$size);#, Connection=>"keep-alive", Keep_Alive=>300);
	undef($/);
	open(F,"< $f") or die $!;
	print <F>;
	exit(0);
}

my $style="/tactical-large.css";#qq%\nimg {border:0;}%; #body {margin-left:0px; margin-top:0px;}
if(defined($options{xs}) && !($options{xe}<0 || $options{ye}<0 || $options{xe}>100 || $options{ye}>100))
{
#print header(-expires=>'+1d'), start_html(-title=>$title, -style=>$style);
   print AWheader($title, qq(<style type="text/css"><!-- img {border:0;} --></style>));
	my $xe=round($options{xs}+$options{xe}/2);
	my $ye=round($options{ys}+$options{ye}/2);
	my $xs=round($options{xs}-$options{xe}/2);
	my $ys=round($options{ys}-$options{ye}/2);
	print qq!<table border="0" cellspacing="0" cellpadding="0" bgcolor='#000000'>!;
	for(my $my=$ys; $my<$ye; $my++) {
		print "<tr>";
		for(my $mx=$xs; $mx<$xe; $mx++) {
#			print "<td> $mx,$my</td>"
			my $f="star$mx,$my.png";
			my $link="";
			my $linkend="</a>";
			if(! -e $f) {my $n=0;
				if($mx%10<=1) {$n|=2}
				if($my%10<=1) {$n|=1}
				if($mx%10==0||$my%10==0) {$n=3}
				$f="/$n.gif";
				$link=qq!<a href="?xs=$mx&amp;ys=$my&amp;xe=$options{xe}&amp;ye=$options{ye}&amp;fast=$options{fast}">!;
			} else {
				$f="?x=$mx&amp;y=$my";
            if($options{fast}) {
               $f="bmw/tactical-large.pl?x=$mx&amp;y=$my";
               #$f="http://aw.lsmod.de:2349/tactical-large.pl?x=$mx&y=$my";
            }
				$link=qq!<a href="system-info?mapx=$mx&amp;mapy=$my">!;}
			my $formatstr="";
			if($my==$ys || $mx==$xs) {$formatstr=qq! height="$imgsize" width="$imgsize"!}
			print qq!<td>$link<img src="$f"$formatstr alt="" />$linkend</td>!;
		}
		print "</tr>\n";
	}
	print "</table>";
} else {
	print header(), AWheader2($title);
	print start_form(-method=>'get', -name=>"form"), 
	 awmapcoordinput(),
    checkbox(-name=>'fast', -label=>'fast', -checked=>1, -value=>'1'), " - uncheck when images are missing",br,
	 submit(-name=>"draw", -class=>'smbutton'), end_form();
}
print end_html;
