#!/usr/bin/perl
# safe 070204
use strict;
use CGI ":standard";

my $max=5000;
#if(!$ENV{REMOTE_USER}) {$ENV{REMOTE_USER}="af"}
my $title="live tactical map [\U$ENV{REMOTE_USER}\E]";
my %options;
BEGIN {chdir "/home/aw/inc";}
use awstandard;
use awinput;
use awmap;
use awmapcgi;
use awmapfunc;
use awdraw2;
awstandard_init();

for my $p (qw'map xs ys xe ye scale') {
	$options{$p}=param($p);
   $options{$p}=~s/[^-+0-9.]//g; # sanitize user input
}
my $xsize=$options{xe};
my $ysize=$options{ye};
my $done;
if(defined($options{xs}) && $options{scale}>0 && $options{scale}<=5 && $xsize>0 && $ysize>0 && $xsize*$ysize<=$max) { # validity checks
 if($options{map}==1) {
	use bytes;
	if($xsize>0 && $ysize>0 && $xsize*$ysize<=$max) {
		$options{xs}-=$xsize>>1;
		$options{ys}-=$ysize>>1;
      awinput_init(1);
		my $png=mapimage($options{xs},$options{ys},$options{xs}+$xsize-1,$options{ys}+$ysize, $options{scale}, undef, \&awfilterchain, [\&awrelationfunc, \&awplanfunc, \&awsiegefunc])->png();
      awinput::awinput_finish();
		my $size=length($png);
		print header(-type=>'image/png', -expires=>"+1h", -content_lenth=>$size), $png;
      $done++;
	}
	$options{map}=0;
 }
 if(!$done) {
  my $xsize=$options{xe}>>1;
  my $ysize=$options{ye}>>1;
  my $totx=bmwround(13*$options{xe});
  my $toty=bmwround(13*$options{ye});
  param("xs", $options{xs}-$xsize);
  param("ys", $options{ys}-$ysize);
  print header(-expires=>"+1h"), 
	start_html(-title=>$title , -style=>"/code/css/tools/tactical.css"), 
	#AWheader2($title),
	start_form('get', "coord"),
   image_button(-src=>"?map=1&xs=$options{xs}&ys=$options{ys}&xe=$options{xe}&ye=$options{ye}&scale=$options{scale}"),
#	qq!<input type="image" src="?map=1&amp;xs=$options{xs}&amp;ys=$options{ys}&amp;xe=$options{xe}&amp;ye=$options{ye}&amp;scale=$options{scale}" />!,
	hidden("xs"),
	hidden("ys"),
	hidden("scale"),
qq%<script language="JavaScript1.2" type="text/javascript">
<!--
var IE = document.all?true:false
if (!IE) document.captureEvents(Event.MOUSEMOVE)
document.onmousemove = getMouseXY;
var tempX = 0
var tempY = 0
function getMouseXY(e) {
  if (IE) {
    tempX = event.clientX + document.body.scrollLeft
    tempY = event.clientY + document.body.scrollTop
  } else {
    tempX = e.pageX
    tempY = e.pageY
  }
  window.status="("+Math.floor((tempX-0)/$options{scale}/$::pixelpersystem+($options{xs}-$xsize))+","+Math.floor((tempY-0)/$options{scale}/$::pixelpersystem+($options{ys}-$ysize))+")"
  return true
}
//--></script>%
	,end_form, end_html;
   $done++;
 }
}
if(!$done) {
   awinput_init(1);
	my $s=5;
	print AWheader($title),start_form(-method=>'get', -name=>"form"),
    awmapcgi::awmapcoordinput(),
	 hidden("map",2),
	 popup_menu(-name=>'scale',-values=>[1,1.5,2,2.5,3,4])." scaling factor".br,
	 submit(-name=>"draw", -class=>'smbutton'), " (up to $max squares)";
	 end_form, end_html;

   awinput::awinput_finish();
}
