#!/usr/bin/perl
use strict;
use CGI ":standard";

my $max=1600;
if(!$ENV{REMOTE_USER}) {$ENV{REMOTE_USER}="af"}
my $title="live tactical map [\U$ENV{REMOTE_USER}\E]";
my %options;
chdir "/home/bernhard/code/cvs/perl/awcalc";
require "awmap.pm";
require "awmapcgi.pm";
#require "standard.pm";
require "cgicommon.pm";

for my $p (qw'map xs ys xe ye scale') {
	$options{$p}=param($p);
}
my $xsize=$options{xe};
my $ysize=$options{ye};
if(defined($options{xs}) && $options{scale}>0 && $options{scale}<5 && $xsize>0 && $ysize>0 && $xsize*$ysize<=$max) { # validity checks
 if($options{map}==1) {
	use bytes;
	require "awdraw.pm";
	if($xsize>0 && $ysize>0 && $xsize*$ysize<=$max) {
		$options{xs}-=$xsize>>1;
		$options{ys}-=$ysize>>1;
		my $png=mapimage($options{xs},$options{ys},$options{xs}+$xsize-1,$options{ys}+$ysize-1, $options{scale})->png();
		my $size=length($png);
		print header(-type=>'image/png', -expires=>"+1h", -content_lenth=>$size), $png;
		exit 0;
	}
	$options{map}==0;
 }
 if($options{map}==2) {
  my $xsize=$options{xe}>>1;
  my $ysize=$options{ye}>>1;
  param("xs", $options{xs}-$xsize);
  param("ys", $options{ys}-$ysize);
  print header(-expires=>"+1h"), 
	start_html(-title=>$title , -style=>"/tactical.css"), 
	#AWheader2($title),
	start_form('get', "coord"),
	qq!<input type="image" src="?map=1&amp;xs=$options{xs}&amp;ys=$options{ys}&amp;xe=$options{xe}&amp;ye=$options{ye}&amp;scale=$options{scale}" />!,
	hidden("xs"),
	hidden("ys"),
	hidden("scale"),
qq%<script language="JavaScript1.2" type="text/javascript">
<!--
var IE = document.all?true:false
if (!IE) document.captureEvents(Event.MOUSEMOVE)
document.onmousemove = getMouseXY;
var tempX = 0
var tempY = 0
function getMouseXY(e) {
  if (IE) {
    tempX = event.clientX + document.body.scrollLeft
    tempY = event.clientY + document.body.scrollTop
  } else {
    tempX = e.pageX
    tempY = e.pageY
  }
  window.status="("+Math.floor((tempX-0)/$options{scale}/$::pixelpersystem+($options{xs}-$xsize))+","+Math.floor((tempY-0)/$options{scale}/$::pixelpersystem+($options{ys}-$ysize))+")"
  return true
}
//--></script>%
	,end_form, end_html;
	exit(0);
 }
}
	my $s=5;
	print AWheader($title),start_form('get'),
	 hidden("map",2),
	 awmapcoordinput(),
	 #textfield(-name=>"xs", -size=>$s)," x&nbsp;&nbsp; ",textfield(-name=>"ys", -size=>$s)," y",br,
	 #textfield(-name=>"xe", -size=>$s)," x&nbsp;&nbsp; ",textfield(-name=>"ye", -size=>$s)," y",br,
	 popup_menu(-name=>'scale',-values=>[1,1.5,2,2.5,3,4])." scaling factor".br,
	 submit(-name=>"draw", -class=>'smbutton'),
	 end_form, end_html;


