#!/usr/bin/perl -w
# safe 070204
# uses modperl/nphperl
use strict;
use warnings;
use mod_perl;
use constant MP2 => ($mod_perl::VERSION >= 1.99);
#use GD;
use awstandard;
#use Apache::RequestRec ();
#use Apache2::RequestIO ();
my ($x,$y,$o)=$ENV{QUERY_STRING}=~m/x=([-+0-9]*)&y=([-+0-9]*)&o=([^=&]*)/;

my $r = shift;
if(0) {
   $r->content_type('text/plain');
   $r->print("error ");
} else {
   my $image;
   my $ret=require "livemap/draw.pm";
   if(!$o) {$o="1,2,3"}
   if(!$ret) {
      $image=`cat $awstandard::htmldir/images/awmaperror.png`;
   } else {
      $o=~s/%2C/,/;
      $o=~s/[^0-9,]//g; # sanitize user input
      $o=[split(",",$o)];
      $image=livemap::draw::draw($x,$y,$o);
   }
   my $size=length($image);
   my $modified=time();
   $r->content_type('image/png');
   $r->set_content_length($size);
   $r->set_keepalive();
   my $timeout=30*60;
   $r->headers_out->set("max-age"=>$timeout);
   $r->headers_out->set("expires"=>awstandard::HTTPdate($modified+$timeout)); #   Sat, 20 Jan 2007 07:12:55 GMT
#   $r->headers_out->set("debug"=>1);
   $r->set_last_modified($modified);
   $r->print($image);
}

1;
