#!/usr/bin/perl -w
use strict;
use CGI ":standard";

use awstandard;
use awinput;
awstandard_init();
#awinput_init();

our %options;
print AWheader("thanks for supporting AWTools");
if(param()) {
	open(my $f, ">>/home/aw/thanks.log");
	foreach my $p (param()) {
		$options{$p}=param($p);
	}
	print $f join(", ", scalar localtime, %options);
} else {
}
print "please also PM greenbird. Sometimes he will have to look into it manually for now (usually takes less than 24 hours).";
print AWtail();

