#!/usr/bin/perl -w
use strict;
use CGI ":standard";
chdir "/home/bernhard/code/cvs/perl/awcalc";
require "standard.pm";
require "cgicommon.pm";

my $sortopts="-k11";
my $round="gold2";
my $titlestr;
if($0=~/topwars/) {
	$titlestr=" wars";
} else {
	$titlestr=" cooperations";
	$sortopts="-r -k5";
}
my $n=50;
my $title="AW $n largest alliance$titlestr";
print AWheader($title);
my $filename="html/$round/alliancerelation";
my $mtime=gmtime((stat($filename))[9]);
print "extracted from ".a({-href=>"/$round/alliancerelation"},"alliancerelation data").br.
	"Last Update $mtime GMT\n".br.
	"alli -- alli // sum(minpop) shared-systems taken-planets lost-planets killed-pop lost-pop friendlyness";

my $data=`sort $sortopts -n $filename | head -$n`;
print pre($data);
print AWtail();
