#!/usr/bin/perl -w
use strict;
use CGI ":standard";
chdir "/home/bernhard/code/cvs/perl/awcalc";
require "standard.pm";
require "cgicommon.pm";

my $sortopts="-k9";
my $titlestr;
if($0=~/topwars/) {
	$titlestr=" wars";
} else {
	$titlestr=" cooperations";
	$sortopts="-r -k5";
}
my $n=50;
my $title="AW $n largest alliance$titlestr";
print AWheader($title);
my $data=`sort $sortopts -n html/beta10/alliancerelation|head -$n`;
print pre($data);
print AWtail();
