#!/usr/bin/perl -w
# safe 070204
use strict;
use CGI qw":standard";
my $title="trade partners [\U$ENV{REMOTE_USER}\E]";

use awstandard;
use awinput;
awinput_init();
use sort_table;
use DBAccess2;

print AWheader($title);

my %options;

for my $p (qw'sort') {
   $options{$p}=param($p);
}
if(!defined $options{sort}){$options{sort}="8.-2";}


our %owntas=();
my $authpid=getauthpid();
if($authpid) {
	$owntas{$authpid}=1;
	my @owntas=awinput::playerid2trades($authpid);
	foreach my $t (@owntas) { $owntas{$t}=1; }
}

sub gettradepartners2($$) { my($maxta,$minad)=@_;
  my @result;
  my $adprice=getartifactprice("pp");
  my $prod=awinput::getallproductionsm();
  foreach my $e (@$prod) {
    my ($pid,$prod,$ad,$pp,$bonus,$arti)=@$e;
    my $name=playerid2namem($pid);
    $ad+=$pp*$adprice;
    if($ad<$minad) {next}
    my $adplus=$ad+(getartifactprice($arti)||0);
    my $trades=awinput::playerid2trades($pid);
    if($trades>$maxta) {next}
    push(@result,[$name,$pid,$ad, $adplus, $prod*$bonus*$adprice, $trades]);
  }
  return @result;
}

#print "test";
my @tap=gettradepartners2(4, 000);
my @tap2;
my $dbh=get_dbh;
my $sth=$dbh->prepare("SELECT COUNT(*) FROM planets
                       WHERE ownerid=? AND population>=14");
foreach my $entry (@tap) {
   my ($name, $pid, $ad, $adplus, $prod, $partners)=@$entry;
   if(!$pid || !$prod) {next}
   my @rel=getrelation($name);
   my $time=(20000-$ad)/$prod;
   my $timeplus=(20000-$adplus)/$prod;
   my ($race)=playerid2ir($pid);
   if($race && @$race && $race->[-3]) {$time=-999.9; $timeplus=-999.9} # traders dont need to save - this sorts them on top of the table
   my ($playerbonus)=$dbh->selectrow_array($sth, {}, $pid);
#   push(@$entry, sprintf("%.2f",$time), $pid, $rel[0]);
	my $cl="-1";
	if(my $player=getplayer($pid)){$cl=$player->{culture}};
   push(@tap2, [$pid, $rel[0], $ad, $prod, $partners, $time, $adplus, $timeplus, $playerbonus,$cl, $owntas{$pid}?"X":"o"]);
}

print sort_table([qw(who relation A$ prod/h partners ready(h) A$+arti ready+arti pop14 culture TA)], 
         [\&display_pid, \&display_relation, \&display_round0, \&display_round0, \&display_string, \&display_round1, \&display_round0, \&display_round1, \&display_string, \&display_string, \&display_string],
         [\&sort_pid, \&sort_num, \&sort_num, \&sort_num, \&sort_num, \&sort_num, \&sort_num, \&sort_num, \&sort_num, \&sort_num, \&sort_string],
         sort_param_to_keys($options{sort}), \@tap2 );

print AWtail();
