#!/usr/bin/perl
# safe 070204
use strict;
use CGI ":standard";

use awstandard;
use awinput;
use sort_table;
awinput_init();

if(param) {
my $alli=$ENV{REMOTE_USER};
my %options;
for my $p (qw'sort sid bio25') {
   $options{$p}=param($p);
}
if(!defined $options{sort}){$options{sort}="-6.-7.8";}
my($sysid)=($options{sid}=~m/(\d+)/);
my $wantbio25=($options{bio25}!=0);
my @sysxy=systemid2coord($sysid);
if(!defined($sysxy[0])) {
   print AWheader("$sysid not found").AWtail();
   exit(0); # modperl OK
}

open(IN, "whocansee.pl $sysid $alli $wantbio25 |") or die $!;
my @data=<IN>;
close(IN);
foreach(@data) {chop; $_=[split(/\t/,$_)]}

print header().AWheader3("Who can see $sysid [\U$alli]", 
      "Who can see system ".a({-href=>"system-info?id=$sysid"},$sysid)." [\U$alli]");
#      " system ".a({-href=>"system-info?id=$sysid"},$sysid);
$wantbio25=!$wantbio25;
print a({-href=>"?sid=$sysid&bio25=$wantbio25"},($wantbio25?"in":"ex")."clude bio25 players").br;


my @data2;
foreach(@data) {
	my($x,$y,$ename,$epid,$esl,$ebio,$rel)=@$_;
   my $dist=sprintf("%.2f", sqrt(($x-$sysxy[0])**2 + ($y-$sysxy[1])**2));
   $rel||=4;
   my $etc=awinput::playername2etc(playerid2name($epid));
   my $p=$player{$epid};
   my $planets=playerid2planets($epid);
   my $needplanets=$$p{culture}-$planets;
   push(@data2, [$epid, $x, $y, $ebio, $dist, $rel, $needplanets, $etc]);
}
 
print sort_table([qw(who x y bio dist relation need ETC)],
         [\&display_pid, \&display_string, \&display_string, \&display_string, \&display_string, \&display_relation, \&display_needplanets, \&display_etc],
         [\&sort_pid, \&sort_num, \&sort_num, \&sort_num, \&sort_num, \&sort_num, \&sort_num, \&sort_num],
         sort_param_to_keys($options{sort}), \@data2);

} else {
   print AWheader("who can see");
   print start_form(-name=>"form", -method=>"get"),textfield(-name=>'sid', -class=>'text'),br,
               submit(-name=>"query", -class=>'smbutton'),end_form.AWfocus("form.sid");
}
print AWtail();
