#!/usr/bin/perl

use strict;
use CGI ":standard";
BEGIN {chdir "/home/bernhard/code/cvs/perl/awcalc";}
use awstandard;
use awinput;
use sort_table;
awinput_init();

my $alli=$ENV{REMOTE_USER};
my %options;
for my $p (qw'sort sid') {
   $options{$p}=param($p);
}
if(!defined $options{sort}){$options{sort}="-6.5";}
my $sysid=$options{sid};
my @sysxy=systemid2coord($sysid);
if(!defined($sysxy[0])) {
   print AWheader("$sysid not found");
   exit(0);
}

open(IN, "whocansee.pl $sysid |") or die $!;
my @data=<IN>;
close(IN);
foreach(@data) {$_=[split(" ",$_)]}

print header().AWheader3("Who can see $sysid [\U$alli]", 
      "Who can see system ".a({-href=>"system-info?id=$sysid"},$sysid)." [\U$alli]");
#      " system ".a({-href=>"system-info?id=$sysid"},$sysid);


my @data2;
foreach(@data) {
	my($x,$y,$ename,$epid,$esl,$ebio,$rel)=@$_;
   my $dist=sprintf("%.2f", sqrt(($x-$sysxy[0])**2 + ($y-$sysxy[1])**2));
   push(@data2, [$epid, $x, $y, $ebio, $dist, $rel]);
}
 
print sort_table([qw(who x y bio dist relation)],
         [\&display_pid, \&display_string, \&display_string, \&display_string, \&display_string, \&display_string],
         [\&sort_pid, \&sort_num, \&sort_num, \&sort_num, \&sort_num, \&sort_num],
         sort_param_to_keys($options{sort}), \@data2);

print AWtail();
