#!/usr/bin/perl -w
use strict;
use DBAccess;

#print "cleaning fleets\n";
# alternatively set all moving fleets outdated
my $time=time()-300;
my $result=$DBAccess::dbh->do("UPDATE `fleets` 
   SET `iscurrent` = 0 
   WHERE `eta` > 0 AND `eta` < $time AND `iscurrent` = 1");

#print "$result cleaned\n";

